github:
  protected_branches:
    develop:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 3
    master:
      foo: bar