// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * Client SDK version.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Client SDK version.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * Programming language of the client SDK.
   * </pre>
   *
   * <code>string language = 3;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * Programming language of the client SDK.
   * </pre>
   *
   * <code>string language = 3;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * Hostname of the client.
   * </pre>
   *
   * <code>string hostname = 4;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <pre>
   * Hostname of the client.
   * </pre>
   *
   * <code>string hostname = 4;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <pre>
   * Source IP address observed by the server.
   * </pre>
   *
   * <code>string egress_ip = 5;</code>
   * @return The egressIp.
   */
  java.lang.String getEgressIp();
  /**
   * <pre>
   * Source IP address observed by the server.
   * </pre>
   *
   * <code>string egress_ip = 5;</code>
   * @return The bytes for egressIp.
   */
  com.google.protobuf.ByteString
      getEgressIpBytes();

  /**
   * <pre>
   * Consumption model, only meaningful for consumers.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.MessageModel message_model = 6;</code>
   * @return The enum numeric value on the wire for messageModel.
   */
  int getMessageModelValue();
  /**
   * <pre>
   * Consumption model, only meaningful for consumers.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.MessageModel message_model = 6;</code>
   * @return The messageModel.
   */
  apache.rocketmq.v2.MessageModel getMessageModel();
}
