// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface DescribeSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.DescribeSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  apache.rocketmq.v2.Status getStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>repeated .apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo client_subscription_info = 2;</code>
   */
  java.util.List<apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo> 
      getClientSubscriptionInfoList();
  /**
   * <code>repeated .apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo client_subscription_info = 2;</code>
   */
  apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo getClientSubscriptionInfo(int index);
  /**
   * <code>repeated .apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo client_subscription_info = 2;</code>
   */
  int getClientSubscriptionInfoCount();
  /**
   * <code>repeated .apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo client_subscription_info = 2;</code>
   */
  java.util.List<? extends apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfoOrBuilder> 
      getClientSubscriptionInfoOrBuilderList();
  /**
   * <code>repeated .apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfo client_subscription_info = 2;</code>
   */
  apache.rocketmq.v2.DescribeSubscriptionResponse.ClientSubscriptionInfoOrBuilder getClientSubscriptionInfoOrBuilder(
      int index);
}
