// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface GetConsumerRunningInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.GetConsumerRunningInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  apache.rocketmq.v2.Status getStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.apache.rocketmq.v2.ConsumerRunningInfo consumer_running_info = 2;</code>
   * @return Whether the consumerRunningInfo field is set.
   */
  boolean hasConsumerRunningInfo();
  /**
   * <code>.apache.rocketmq.v2.ConsumerRunningInfo consumer_running_info = 2;</code>
   * @return The consumerRunningInfo.
   */
  apache.rocketmq.v2.ConsumerRunningInfo getConsumerRunningInfo();
  /**
   * <code>.apache.rocketmq.v2.ConsumerRunningInfo consumer_running_info = 2;</code>
   */
  apache.rocketmq.v2.ConsumerRunningInfoOrBuilder getConsumerRunningInfoOrBuilder();
}
