// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface GetProxyRuntimeStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.GetProxyRuntimeStatsRequest)
    com.google.protobuf.MessageOrBuilder {
}
