// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface ListMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.ListMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  apache.rocketmq.v2.Status getStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  java.util.List<apache.rocketmq.v2.Message> 
      getMessagesList();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  apache.rocketmq.v2.Message getMessages(int index);
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  java.util.List<? extends apache.rocketmq.v2.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  apache.rocketmq.v2.MessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * Cursor to be passed back to fetch the next page.
   * </pre>
   *
   * <code>string scroll_id = 3;</code>
   * @return The scrollId.
   */
  java.lang.String getScrollId();
  /**
   * <pre>
   * Cursor to be passed back to fetch the next page.
   * </pre>
   *
   * <code>string scroll_id = 3;</code>
   * @return The bytes for scrollId.
   */
  com.google.protobuf.ByteString
      getScrollIdBytes();
}
