// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    body_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.Resource.Builder subBuilder = null;
            if (topic_ != null) {
              subBuilder = topic_.toBuilder();
            }
            topic_ = input.readMessage(apache.rocketmq.v2.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(topic_);
              topic_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              userProperties_ = com.google.protobuf.MapField.newMapField(
                  UserPropertiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            userProperties__ = input.readMessage(
                UserPropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            userProperties_.getMutableMap().put(
                userProperties__.getKey(), userProperties__.getValue());
            break;
          }
          case 26: {
            apache.rocketmq.v2.SystemProperties.Builder subBuilder = null;
            if (systemProperties_ != null) {
              subBuilder = systemProperties_.toBuilder();
            }
            systemProperties_ = input.readMessage(apache.rocketmq.v2.SystemProperties.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(systemProperties_);
              systemProperties_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {

            body_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetUserProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.Message.class, apache.rocketmq.v2.Message.Builder.class);
  }

  public static final int TOPIC_FIELD_NUMBER = 1;
  private apache.rocketmq.v2.Resource topic_;
  /**
   * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
   * @return Whether the topic field is set.
   */
  @java.lang.Override
  public boolean hasTopic() {
    return topic_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
   * @return The topic.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Resource getTopic() {
    return topic_ == null ? apache.rocketmq.v2.Resource.getDefaultInstance() : topic_;
  }
  /**
   * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ResourceOrBuilder getTopicOrBuilder() {
    return getTopic();
  }

  public static final int USER_PROPERTIES_FIELD_NUMBER = 2;
  private static final class UserPropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_UserPropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> userProperties_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetUserProperties() {
    if (userProperties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UserPropertiesDefaultEntryHolder.defaultEntry);
    }
    return userProperties_;
  }

  public int getUserPropertiesCount() {
    return internalGetUserProperties().getMap().size();
  }
  /**
   * <pre>
   * User defined key-value pairs.
   * If user_properties contain the reserved keys by RocketMQ,
   * the send message request will be aborted with status `INVALID_ARGUMENT`.
   * See below links for the reserved keys
   * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
   * </pre>
   *
   * <code>map&lt;string, string&gt; user_properties = 2;</code>
   */

  @java.lang.Override
  public boolean containsUserProperties(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetUserProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUserPropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getUserProperties() {
    return getUserPropertiesMap();
  }
  /**
   * <pre>
   * User defined key-value pairs.
   * If user_properties contain the reserved keys by RocketMQ,
   * the send message request will be aborted with status `INVALID_ARGUMENT`.
   * See below links for the reserved keys
   * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
   * </pre>
   *
   * <code>map&lt;string, string&gt; user_properties = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getUserPropertiesMap() {
    return internalGetUserProperties().getMap();
  }
  /**
   * <pre>
   * User defined key-value pairs.
   * If user_properties contain the reserved keys by RocketMQ,
   * the send message request will be aborted with status `INVALID_ARGUMENT`.
   * See below links for the reserved keys
   * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
   * </pre>
   *
   * <code>map&lt;string, string&gt; user_properties = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getUserPropertiesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUserProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * User defined key-value pairs.
   * If user_properties contain the reserved keys by RocketMQ,
   * the send message request will be aborted with status `INVALID_ARGUMENT`.
   * See below links for the reserved keys
   * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
   * </pre>
   *
   * <code>map&lt;string, string&gt; user_properties = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getUserPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUserProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SYSTEM_PROPERTIES_FIELD_NUMBER = 3;
  private apache.rocketmq.v2.SystemProperties systemProperties_;
  /**
   * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
   * @return Whether the systemProperties field is set.
   */
  @java.lang.Override
  public boolean hasSystemProperties() {
    return systemProperties_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
   * @return The systemProperties.
   */
  @java.lang.Override
  public apache.rocketmq.v2.SystemProperties getSystemProperties() {
    return systemProperties_ == null ? apache.rocketmq.v2.SystemProperties.getDefaultInstance() : systemProperties_;
  }
  /**
   * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.SystemPropertiesOrBuilder getSystemPropertiesOrBuilder() {
    return getSystemProperties();
  }

  public static final int BODY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 4;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topic_ != null) {
      output.writeMessage(1, getTopic());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUserProperties(),
        UserPropertiesDefaultEntryHolder.defaultEntry,
        2);
    if (systemProperties_ != null) {
      output.writeMessage(3, getSystemProperties());
    }
    if (!body_.isEmpty()) {
      output.writeBytes(4, body_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topic_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTopic());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetUserProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      userProperties__ = UserPropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, userProperties__);
    }
    if (systemProperties_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSystemProperties());
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, body_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.Message)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.Message other = (apache.rocketmq.v2.Message) obj;

    if (hasTopic() != other.hasTopic()) return false;
    if (hasTopic()) {
      if (!getTopic()
          .equals(other.getTopic())) return false;
    }
    if (!internalGetUserProperties().equals(
        other.internalGetUserProperties())) return false;
    if (hasSystemProperties() != other.hasSystemProperties()) return false;
    if (hasSystemProperties()) {
      if (!getSystemProperties()
          .equals(other.getSystemProperties())) return false;
    }
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTopic()) {
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
    }
    if (!internalGetUserProperties().getMap().isEmpty()) {
      hash = (37 * hash) + USER_PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUserProperties().hashCode();
    }
    if (hasSystemProperties()) {
      hash = (37 * hash) + SYSTEM_PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + getSystemProperties().hashCode();
    }
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.Message)
      apache.rocketmq.v2.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetUserProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableUserProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.Message.class, apache.rocketmq.v2.Message.Builder.class);
    }

    // Construct using apache.rocketmq.v2.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (topicBuilder_ == null) {
        topic_ = null;
      } else {
        topic_ = null;
        topicBuilder_ = null;
      }
      internalGetMutableUserProperties().clear();
      if (systemPropertiesBuilder_ == null) {
        systemProperties_ = null;
      } else {
        systemProperties_ = null;
        systemPropertiesBuilder_ = null;
      }
      body_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Message_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.Message getDefaultInstanceForType() {
      return apache.rocketmq.v2.Message.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.Message build() {
      apache.rocketmq.v2.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.Message buildPartial() {
      apache.rocketmq.v2.Message result = new apache.rocketmq.v2.Message(this);
      int from_bitField0_ = bitField0_;
      if (topicBuilder_ == null) {
        result.topic_ = topic_;
      } else {
        result.topic_ = topicBuilder_.build();
      }
      result.userProperties_ = internalGetUserProperties();
      result.userProperties_.makeImmutable();
      if (systemPropertiesBuilder_ == null) {
        result.systemProperties_ = systemProperties_;
      } else {
        result.systemProperties_ = systemPropertiesBuilder_.build();
      }
      result.body_ = body_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.Message) {
        return mergeFrom((apache.rocketmq.v2.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.Message other) {
      if (other == apache.rocketmq.v2.Message.getDefaultInstance()) return this;
      if (other.hasTopic()) {
        mergeTopic(other.getTopic());
      }
      internalGetMutableUserProperties().mergeFrom(
          other.internalGetUserProperties());
      if (other.hasSystemProperties()) {
        mergeSystemProperties(other.getSystemProperties());
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private apache.rocketmq.v2.Resource topic_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder> topicBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     * @return Whether the topic field is set.
     */
    public boolean hasTopic() {
      return topicBuilder_ != null || topic_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     * @return The topic.
     */
    public apache.rocketmq.v2.Resource getTopic() {
      if (topicBuilder_ == null) {
        return topic_ == null ? apache.rocketmq.v2.Resource.getDefaultInstance() : topic_;
      } else {
        return topicBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public Builder setTopic(apache.rocketmq.v2.Resource value) {
      if (topicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        topic_ = value;
        onChanged();
      } else {
        topicBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public Builder setTopic(
        apache.rocketmq.v2.Resource.Builder builderForValue) {
      if (topicBuilder_ == null) {
        topic_ = builderForValue.build();
        onChanged();
      } else {
        topicBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public Builder mergeTopic(apache.rocketmq.v2.Resource value) {
      if (topicBuilder_ == null) {
        if (topic_ != null) {
          topic_ =
            apache.rocketmq.v2.Resource.newBuilder(topic_).mergeFrom(value).buildPartial();
        } else {
          topic_ = value;
        }
        onChanged();
      } else {
        topicBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public Builder clearTopic() {
      if (topicBuilder_ == null) {
        topic_ = null;
        onChanged();
      } else {
        topic_ = null;
        topicBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public apache.rocketmq.v2.Resource.Builder getTopicBuilder() {
      
      onChanged();
      return getTopicFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    public apache.rocketmq.v2.ResourceOrBuilder getTopicOrBuilder() {
      if (topicBuilder_ != null) {
        return topicBuilder_.getMessageOrBuilder();
      } else {
        return topic_ == null ?
            apache.rocketmq.v2.Resource.getDefaultInstance() : topic_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Resource topic = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder> 
        getTopicFieldBuilder() {
      if (topicBuilder_ == null) {
        topicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder>(
                getTopic(),
                getParentForChildren(),
                isClean());
        topic_ = null;
      }
      return topicBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> userProperties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetUserProperties() {
      if (userProperties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserPropertiesDefaultEntryHolder.defaultEntry);
      }
      return userProperties_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableUserProperties() {
      onChanged();;
      if (userProperties_ == null) {
        userProperties_ = com.google.protobuf.MapField.newMapField(
            UserPropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!userProperties_.isMutable()) {
        userProperties_ = userProperties_.copy();
      }
      return userProperties_;
    }

    public int getUserPropertiesCount() {
      return internalGetUserProperties().getMap().size();
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */

    @java.lang.Override
    public boolean containsUserProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetUserProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getUserProperties() {
      return getUserPropertiesMap();
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getUserPropertiesMap() {
      return internalGetUserProperties().getMap();
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getUserPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetUserProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getUserPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetUserProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUserProperties() {
      internalGetMutableUserProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */

    public Builder removeUserProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableUserProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableUserProperties() {
      return internalGetMutableUserProperties().getMutableMap();
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */
    public Builder putUserProperties(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableUserProperties().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * User defined key-value pairs.
     * If user_properties contain the reserved keys by RocketMQ,
     * the send message request will be aborted with status `INVALID_ARGUMENT`.
     * See below links for the reserved keys
     * https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java#L58
     * </pre>
     *
     * <code>map&lt;string, string&gt; user_properties = 2;</code>
     */

    public Builder putAllUserProperties(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableUserProperties().getMutableMap()
          .putAll(values);
      return this;
    }

    private apache.rocketmq.v2.SystemProperties systemProperties_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.SystemProperties, apache.rocketmq.v2.SystemProperties.Builder, apache.rocketmq.v2.SystemPropertiesOrBuilder> systemPropertiesBuilder_;
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     * @return Whether the systemProperties field is set.
     */
    public boolean hasSystemProperties() {
      return systemPropertiesBuilder_ != null || systemProperties_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     * @return The systemProperties.
     */
    public apache.rocketmq.v2.SystemProperties getSystemProperties() {
      if (systemPropertiesBuilder_ == null) {
        return systemProperties_ == null ? apache.rocketmq.v2.SystemProperties.getDefaultInstance() : systemProperties_;
      } else {
        return systemPropertiesBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public Builder setSystemProperties(apache.rocketmq.v2.SystemProperties value) {
      if (systemPropertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        systemProperties_ = value;
        onChanged();
      } else {
        systemPropertiesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public Builder setSystemProperties(
        apache.rocketmq.v2.SystemProperties.Builder builderForValue) {
      if (systemPropertiesBuilder_ == null) {
        systemProperties_ = builderForValue.build();
        onChanged();
      } else {
        systemPropertiesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public Builder mergeSystemProperties(apache.rocketmq.v2.SystemProperties value) {
      if (systemPropertiesBuilder_ == null) {
        if (systemProperties_ != null) {
          systemProperties_ =
            apache.rocketmq.v2.SystemProperties.newBuilder(systemProperties_).mergeFrom(value).buildPartial();
        } else {
          systemProperties_ = value;
        }
        onChanged();
      } else {
        systemPropertiesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public Builder clearSystemProperties() {
      if (systemPropertiesBuilder_ == null) {
        systemProperties_ = null;
        onChanged();
      } else {
        systemProperties_ = null;
        systemPropertiesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public apache.rocketmq.v2.SystemProperties.Builder getSystemPropertiesBuilder() {
      
      onChanged();
      return getSystemPropertiesFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    public apache.rocketmq.v2.SystemPropertiesOrBuilder getSystemPropertiesOrBuilder() {
      if (systemPropertiesBuilder_ != null) {
        return systemPropertiesBuilder_.getMessageOrBuilder();
      } else {
        return systemProperties_ == null ?
            apache.rocketmq.v2.SystemProperties.getDefaultInstance() : systemProperties_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.SystemProperties system_properties = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.SystemProperties, apache.rocketmq.v2.SystemProperties.Builder, apache.rocketmq.v2.SystemPropertiesOrBuilder> 
        getSystemPropertiesFieldBuilder() {
      if (systemPropertiesBuilder_ == null) {
        systemPropertiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.SystemProperties, apache.rocketmq.v2.SystemProperties.Builder, apache.rocketmq.v2.SystemPropertiesOrBuilder>(
                getSystemProperties(),
                getParentForChildren(),
                isClean());
        systemProperties_ = null;
      }
      return systemPropertiesBuilder_;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 4;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 4;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.Message)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.Message)
  private static final apache.rocketmq.v2.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.Message();
  }

  public static apache.rocketmq.v2.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

