// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

/**
 * <pre>
 * A message queue together with the process queue snapshot held by a consumer.
 * </pre>
 *
 * Protobuf type {@code apache.rocketmq.v2.MessageQueueItem}
 */
public final class MessageQueueItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.MessageQueueItem)
    MessageQueueItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageQueueItem.newBuilder() to construct.
  private MessageQueueItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageQueueItem() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageQueueItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageQueueItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.MessageQueue.Builder subBuilder = null;
            if (messageQueue_ != null) {
              subBuilder = messageQueue_.toBuilder();
            }
            messageQueue_ = input.readMessage(apache.rocketmq.v2.MessageQueue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageQueue_);
              messageQueue_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            apache.rocketmq.v2.ProcessQueueInfo.Builder subBuilder = null;
            if (processQueueInfo_ != null) {
              subBuilder = processQueueInfo_.toBuilder();
            }
            processQueueInfo_ = input.readMessage(apache.rocketmq.v2.ProcessQueueInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(processQueueInfo_);
              processQueueInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQAdmin.internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQAdmin.internal_static_apache_rocketmq_v2_MessageQueueItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.MessageQueueItem.class, apache.rocketmq.v2.MessageQueueItem.Builder.class);
  }

  public static final int MESSAGE_QUEUE_FIELD_NUMBER = 1;
  private apache.rocketmq.v2.MessageQueue messageQueue_;
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
   * @return Whether the messageQueue field is set.
   */
  @java.lang.Override
  public boolean hasMessageQueue() {
    return messageQueue_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
   * @return The messageQueue.
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageQueue getMessageQueue() {
    return messageQueue_ == null ? apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
  }
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageQueueOrBuilder getMessageQueueOrBuilder() {
    return getMessageQueue();
  }

  public static final int PROCESS_QUEUE_INFO_FIELD_NUMBER = 2;
  private apache.rocketmq.v2.ProcessQueueInfo processQueueInfo_;
  /**
   * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
   * @return Whether the processQueueInfo field is set.
   */
  @java.lang.Override
  public boolean hasProcessQueueInfo() {
    return processQueueInfo_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
   * @return The processQueueInfo.
   */
  @java.lang.Override
  public apache.rocketmq.v2.ProcessQueueInfo getProcessQueueInfo() {
    return processQueueInfo_ == null ? apache.rocketmq.v2.ProcessQueueInfo.getDefaultInstance() : processQueueInfo_;
  }
  /**
   * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ProcessQueueInfoOrBuilder getProcessQueueInfoOrBuilder() {
    return getProcessQueueInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageQueue_ != null) {
      output.writeMessage(1, getMessageQueue());
    }
    if (processQueueInfo_ != null) {
      output.writeMessage(2, getProcessQueueInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageQueue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessageQueue());
    }
    if (processQueueInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getProcessQueueInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.MessageQueueItem)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.MessageQueueItem other = (apache.rocketmq.v2.MessageQueueItem) obj;

    if (hasMessageQueue() != other.hasMessageQueue()) return false;
    if (hasMessageQueue()) {
      if (!getMessageQueue()
          .equals(other.getMessageQueue())) return false;
    }
    if (hasProcessQueueInfo() != other.hasProcessQueueInfo()) return false;
    if (hasProcessQueueInfo()) {
      if (!getProcessQueueInfo()
          .equals(other.getProcessQueueInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessageQueue()) {
      hash = (37 * hash) + MESSAGE_QUEUE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageQueue().hashCode();
    }
    if (hasProcessQueueInfo()) {
      hash = (37 * hash) + PROCESS_QUEUE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getProcessQueueInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.MessageQueueItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.MessageQueueItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A message queue together with the process queue snapshot held by a consumer.
   * </pre>
   *
   * Protobuf type {@code apache.rocketmq.v2.MessageQueueItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.MessageQueueItem)
      apache.rocketmq.v2.MessageQueueItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQAdmin.internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQAdmin.internal_static_apache_rocketmq_v2_MessageQueueItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.MessageQueueItem.class, apache.rocketmq.v2.MessageQueueItem.Builder.class);
    }

    // Construct using apache.rocketmq.v2.MessageQueueItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageQueueBuilder_ == null) {
        messageQueue_ = null;
      } else {
        messageQueue_ = null;
        messageQueueBuilder_ = null;
      }
      if (processQueueInfoBuilder_ == null) {
        processQueueInfo_ = null;
      } else {
        processQueueInfo_ = null;
        processQueueInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQAdmin.internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.MessageQueueItem getDefaultInstanceForType() {
      return apache.rocketmq.v2.MessageQueueItem.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.MessageQueueItem build() {
      apache.rocketmq.v2.MessageQueueItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.MessageQueueItem buildPartial() {
      apache.rocketmq.v2.MessageQueueItem result = new apache.rocketmq.v2.MessageQueueItem(this);
      if (messageQueueBuilder_ == null) {
        result.messageQueue_ = messageQueue_;
      } else {
        result.messageQueue_ = messageQueueBuilder_.build();
      }
      if (processQueueInfoBuilder_ == null) {
        result.processQueueInfo_ = processQueueInfo_;
      } else {
        result.processQueueInfo_ = processQueueInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.MessageQueueItem) {
        return mergeFrom((apache.rocketmq.v2.MessageQueueItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.MessageQueueItem other) {
      if (other == apache.rocketmq.v2.MessageQueueItem.getDefaultInstance()) return this;
      if (other.hasMessageQueue()) {
        mergeMessageQueue(other.getMessageQueue());
      }
      if (other.hasProcessQueueInfo()) {
        mergeProcessQueueInfo(other.getProcessQueueInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.MessageQueueItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.MessageQueueItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private apache.rocketmq.v2.MessageQueue messageQueue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder> messageQueueBuilder_;
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     * @return Whether the messageQueue field is set.
     */
    public boolean hasMessageQueue() {
      return messageQueueBuilder_ != null || messageQueue_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     * @return The messageQueue.
     */
    public apache.rocketmq.v2.MessageQueue getMessageQueue() {
      if (messageQueueBuilder_ == null) {
        return messageQueue_ == null ? apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
      } else {
        return messageQueueBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public Builder setMessageQueue(apache.rocketmq.v2.MessageQueue value) {
      if (messageQueueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageQueue_ = value;
        onChanged();
      } else {
        messageQueueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public Builder setMessageQueue(
        apache.rocketmq.v2.MessageQueue.Builder builderForValue) {
      if (messageQueueBuilder_ == null) {
        messageQueue_ = builderForValue.build();
        onChanged();
      } else {
        messageQueueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public Builder mergeMessageQueue(apache.rocketmq.v2.MessageQueue value) {
      if (messageQueueBuilder_ == null) {
        if (messageQueue_ != null) {
          messageQueue_ =
            apache.rocketmq.v2.MessageQueue.newBuilder(messageQueue_).mergeFrom(value).buildPartial();
        } else {
          messageQueue_ = value;
        }
        onChanged();
      } else {
        messageQueueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public Builder clearMessageQueue() {
      if (messageQueueBuilder_ == null) {
        messageQueue_ = null;
        onChanged();
      } else {
        messageQueue_ = null;
        messageQueueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public apache.rocketmq.v2.MessageQueue.Builder getMessageQueueBuilder() {
      
      onChanged();
      return getMessageQueueFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    public apache.rocketmq.v2.MessageQueueOrBuilder getMessageQueueOrBuilder() {
      if (messageQueueBuilder_ != null) {
        return messageQueueBuilder_.getMessageOrBuilder();
      } else {
        return messageQueue_ == null ?
            apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder> 
        getMessageQueueFieldBuilder() {
      if (messageQueueBuilder_ == null) {
        messageQueueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder>(
                getMessageQueue(),
                getParentForChildren(),
                isClean());
        messageQueue_ = null;
      }
      return messageQueueBuilder_;
    }

    private apache.rocketmq.v2.ProcessQueueInfo processQueueInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ProcessQueueInfo, apache.rocketmq.v2.ProcessQueueInfo.Builder, apache.rocketmq.v2.ProcessQueueInfoOrBuilder> processQueueInfoBuilder_;
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     * @return Whether the processQueueInfo field is set.
     */
    public boolean hasProcessQueueInfo() {
      return processQueueInfoBuilder_ != null || processQueueInfo_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     * @return The processQueueInfo.
     */
    public apache.rocketmq.v2.ProcessQueueInfo getProcessQueueInfo() {
      if (processQueueInfoBuilder_ == null) {
        return processQueueInfo_ == null ? apache.rocketmq.v2.ProcessQueueInfo.getDefaultInstance() : processQueueInfo_;
      } else {
        return processQueueInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public Builder setProcessQueueInfo(apache.rocketmq.v2.ProcessQueueInfo value) {
      if (processQueueInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        processQueueInfo_ = value;
        onChanged();
      } else {
        processQueueInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public Builder setProcessQueueInfo(
        apache.rocketmq.v2.ProcessQueueInfo.Builder builderForValue) {
      if (processQueueInfoBuilder_ == null) {
        processQueueInfo_ = builderForValue.build();
        onChanged();
      } else {
        processQueueInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public Builder mergeProcessQueueInfo(apache.rocketmq.v2.ProcessQueueInfo value) {
      if (processQueueInfoBuilder_ == null) {
        if (processQueueInfo_ != null) {
          processQueueInfo_ =
            apache.rocketmq.v2.ProcessQueueInfo.newBuilder(processQueueInfo_).mergeFrom(value).buildPartial();
        } else {
          processQueueInfo_ = value;
        }
        onChanged();
      } else {
        processQueueInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public Builder clearProcessQueueInfo() {
      if (processQueueInfoBuilder_ == null) {
        processQueueInfo_ = null;
        onChanged();
      } else {
        processQueueInfo_ = null;
        processQueueInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public apache.rocketmq.v2.ProcessQueueInfo.Builder getProcessQueueInfoBuilder() {
      
      onChanged();
      return getProcessQueueInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    public apache.rocketmq.v2.ProcessQueueInfoOrBuilder getProcessQueueInfoOrBuilder() {
      if (processQueueInfoBuilder_ != null) {
        return processQueueInfoBuilder_.getMessageOrBuilder();
      } else {
        return processQueueInfo_ == null ?
            apache.rocketmq.v2.ProcessQueueInfo.getDefaultInstance() : processQueueInfo_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ProcessQueueInfo process_queue_info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ProcessQueueInfo, apache.rocketmq.v2.ProcessQueueInfo.Builder, apache.rocketmq.v2.ProcessQueueInfoOrBuilder> 
        getProcessQueueInfoFieldBuilder() {
      if (processQueueInfoBuilder_ == null) {
        processQueueInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.ProcessQueueInfo, apache.rocketmq.v2.ProcessQueueInfo.Builder, apache.rocketmq.v2.ProcessQueueInfoOrBuilder>(
                getProcessQueueInfo(),
                getParentForChildren(),
                isClean());
        processQueueInfo_ = null;
      }
      return processQueueInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.MessageQueueItem)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.MessageQueueItem)
  private static final apache.rocketmq.v2.MessageQueueItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.MessageQueueItem();
  }

  public static apache.rocketmq.v2.MessageQueueItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageQueueItem>
      PARSER = new com.google.protobuf.AbstractParser<MessageQueueItem>() {
    @java.lang.Override
    public MessageQueueItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageQueueItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageQueueItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageQueueItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.MessageQueueItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

