// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public final class MQAdmin {
  private MQAdmin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeLogLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeLogLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeLogLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeLogLevelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeTopicStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeTopicStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SubscriptionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SubscriptionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_ClientSubscriptionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_ClientSubscriptionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DeleteSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DeleteSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DeleteSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DeleteSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ClientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ClientInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_MessageQueueItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ProcessQueueInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ProcessQueueInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ConsumeStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ConsumeStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_SubscriptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_SubscriptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_ConsumeStatusTableEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_ConsumeStatusTableEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_GroupAccumulation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_GroupAccumulation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_TopicAccumulationEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_TopicAccumulationEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_LiteTopicAccumulationEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_LiteTopicAccumulationEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryTimeSpanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryTimeSpanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_QueueTimeSpan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_QueueTimeSpan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListConsumerConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListConsumerConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListConsumerConnectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListConsumerConnectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ResetGroupOffsetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ResetGroupOffsetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ResetGroupOffsetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ResetGroupOffsetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ListMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ListMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_PrintThreadStackTraceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_PrintThreadStackTraceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AdminSendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_UserPropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AdminSendMessageRequest_UserPropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_ExtInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AdminSendMessageRequest_ExtInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AdminSendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AdminSendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetConsumerRunningInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetConsumerRunningInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetTopicRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetTopicRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetTopicRouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetTopicRouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036apache/rocketmq/v2/admin.proto\022\022apache" +
      ".rocketmq.v2\032\036google/protobuf/duration.p" +
      "roto\032\037google/protobuf/timestamp.proto\032#a" +
      "pache/rocketmq/v2/definition.proto\"\225\001\n\025C" +
      "hangeLogLevelRequest\022>\n\005level\030\001 \001(\0162/.ap" +
      "ache.rocketmq.v2.ChangeLogLevelRequest.L" +
      "evel\"<\n\005Level\022\t\n\005TRACE\020\000\022\t\n\005DEBUG\020\001\022\010\n\004I" +
      "NFO\020\002\022\010\n\004WARN\020\003\022\t\n\005ERROR\020\004\"(\n\026ChangeLogL" +
      "evelResponse\022\016\n\006remark\030\001 \001(\t\"{\n\032Describe" +
      "TopicStatusRequest\022\034\n\017deployment_name\030\001 " +
      "\001(\tH\000\210\001\001\022+\n\005topic\030\002 \001(\0132\034.apache.rocketm" +
      "q.v2.ResourceB\022\n\020_deployment_name\"\366\002\n\033De" +
      "scribeTopicStatusResponse\022*\n\006status\030\001 \001(" +
      "\0132\032.apache.rocketmq.v2.Status\022;\n\022topic_m" +
      "essage_type\030\002 \001(\0162\037.apache.rocketmq.v2.M" +
      "essageType\022\030\n\013description\030\003 \001(\tH\000\210\001\001\0229\n\020" +
      "create_timestamp\030\004 \001(\0132\032.google.protobuf" +
      ".TimestampH\001\210\001\001\022G\n\004tags\030\005 \003(\01329.apache.r" +
      "ocketmq.v2.DescribeTopicStatusResponse.T" +
      "agsEntry\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001B\016\n\014_descriptionB\023\n\021_create" +
      "_timestamp\"\303\001\n\027ListSubscriptionRequest\022\034" +
      "\n\017deployment_name\030\001 \001(\tH\000\210\001\001\0220\n\005topic\030\002 " +
      "\001(\0132\034.apache.rocketmq.v2.ResourceH\001\210\001\001\0220" +
      "\n\005group\030\003 \001(\0132\034.apache.rocketmq.v2.Resou" +
      "rceH\002\210\001\001B\022\n\020_deployment_nameB\010\n\006_topicB\010" +
      "\n\006_group\"\314\002\n\020SubscriptionInfo\022+\n\005group\030\001" +
      " \001(\0132\034.apache.rocketmq.v2.Resource\022+\n\005to" +
      "pic\030\002 \001(\0132\034.apache.rocketmq.v2.Resource\022" +
      "8\n\nexpression\030\003 \001(\0132$.apache.rocketmq.v2" +
      ".FilterExpression\022\016\n\006online\030\004 \001(\010\0229\n\025las" +
      "t_update_timestamp\030\005 \001(\0132\032.google.protob" +
      "uf.Timestamp\0227\n\rmessage_model\030\006 \001(\0162 .ap" +
      "ache.rocketmq.v2.MessageModel\022 \n\030subscri" +
      "ption_consistency\030\007 \001(\010\"\207\001\n\030ListSubscrip" +
      "tionResponse\022*\n\006status\030\001 \001(\0132\032.apache.ro" +
      "cketmq.v2.Status\022?\n\021subscription_info\030\002 " +
      "\003(\0132$.apache.rocketmq.v2.SubscriptionInf" +
      "o\"\307\001\n\033DescribeSubscriptionRequest\022\034\n\017dep" +
      "loyment_name\030\001 \001(\tH\000\210\001\001\0220\n\005topic\030\002 \001(\0132\034" +
      ".apache.rocketmq.v2.ResourceH\001\210\001\001\0220\n\005gro" +
      "up\030\003 \001(\0132\034.apache.rocketmq.v2.ResourceH\002" +
      "\210\001\001B\022\n\020_deployment_nameB\010\n\006_topicB\010\n\006_gr" +
      "oup\"\306\002\n\034DescribeSubscriptionResponse\022*\n\006" +
      "status\030\001 \001(\0132\032.apache.rocketmq.v2.Status" +
      "\022i\n\030client_subscription_info\030\002 \003(\0132G.apa" +
      "che.rocketmq.v2.DescribeSubscriptionResp" +
      "onse.ClientSubscriptionInfo\032\216\001\n\026ClientSu" +
      "bscriptionInfo\0223\n\013client_info\030\001 \001(\0132\036.ap" +
      "ache.rocketmq.v2.ClientInfo\022?\n\021subscript" +
      "ion_info\030\002 \001(\0132$.apache.rocketmq.v2.Subs" +
      "criptionInfo\"\341\001\n\031DeleteSubscriptionReque" +
      "st\022\034\n\017deployment_name\030\001 \001(\tH\000\210\001\001\022+\n\005topi" +
      "c\030\002 \001(\0132\034.apache.rocketmq.v2.Resource\022+\n" +
      "\005group\030\003 \001(\0132\034.apache.rocketmq.v2.Resour" +
      "ce\0228\n\nexpression\030\004 \001(\0132$.apache.rocketmq" +
      ".v2.FilterExpressionB\022\n\020_deployment_name" +
      "\"H\n\032DeleteSubscriptionResponse\022*\n\006status" +
      "\030\001 \001(\0132\032.apache.rocketmq.v2.Status\"\240\001\n\nC" +
      "lientInfo\022\021\n\tclient_id\030\001 \001(\t\022\017\n\007version\030" +
      "\002 \001(\t\022\020\n\010language\030\003 \001(\t\022\020\n\010hostname\030\004 \001(" +
      "\t\022\021\n\tegress_ip\030\005 \001(\t\0227\n\rmessage_model\030\006 " +
      "\001(\0162 .apache.rocketmq.v2.MessageModel\"\215\001" +
      "\n\020MessageQueueItem\0227\n\rmessage_queue\030\001 \001(" +
      "\0132 .apache.rocketmq.v2.MessageQueue\022@\n\022p" +
      "rocess_queue_info\030\002 \001(\0132$.apache.rocketm" +
      "q.v2.ProcessQueueInfo\"\235\003\n\020ProcessQueueIn" +
      "fo\022\025\n\rcommit_offset\030\001 \001(\003\022\035\n\025cached_msg_" +
      "min_offset\030\002 \001(\003\022\035\n\025cached_msg_max_offse" +
      "t\030\003 \001(\003\022\030\n\020cached_msg_count\030\004 \001(\005\022\036\n\026cac" +
      "hed_msg_size_in_mib\030\005 \001(\005\022\"\n\032transaction" +
      "_msg_min_offset\030\006 \001(\003\022\"\n\032transaction_msg" +
      "_max_offset\030\007 \001(\003\022\035\n\025transaction_msg_cou" +
      "nt\030\010 \001(\005\022\016\n\006locked\030\t \001(\010\022\030\n\020try_unlock_t" +
      "imes\030\n \001(\003\022\033\n\023last_lock_timestamp\030\013 \001(\003\022" +
      "\017\n\007dropped\030\014 \001(\010\022\033\n\023last_pull_timestamp\030" +
      "\r \001(\003\022\036\n\026last_consume_timestamp\030\016 \001(\003\"\235\001" +
      "\n\rConsumeStatus\022\022\n\nreceive_rt\030\001 \001(\001\022\023\n\013r" +
      "eceive_tps\030\002 \001(\001\022\022\n\nconsume_rt\030\003 \001(\001\022\026\n\016" +
      "consume_ok_tps\030\004 \001(\001\022\032\n\022consume_failed_t" +
      "ps\030\005 \001(\001\022\033\n\023consume_failed_msgs\030\006 \001(\003\"\304\004" +
      "\n\023ConsumerRunningInfo\022K\n\nproperties\030\001 \003(" +
      "\01327.apache.rocketmq.v2.ConsumerRunningIn" +
      "fo.PropertiesEntry\022Q\n\rsubscriptions\030\002 \003(" +
      "\0132:.apache.rocketmq.v2.ConsumerRunningIn" +
      "fo.SubscriptionsEntry\022A\n\023message_queue_t" +
      "able\030\003 \003(\0132$.apache.rocketmq.v2.MessageQ" +
      "ueueItem\022]\n\024consume_status_table\030\004 \003(\0132?" +
      ".apache.rocketmq.v2.ConsumerRunningInfo." +
      "ConsumeStatusTableEntry\0321\n\017PropertiesEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032Z\n\022Su" +
      "bscriptionsEntry\022\013\n\003key\030\001 \001(\t\0223\n\005value\030\002" +
      " \001(\0132$.apache.rocketmq.v2.FilterExpressi" +
      "on:\0028\001\032\\\n\027ConsumeStatusTableEntry\022\013\n\003key" +
      "\030\001 \001(\t\0220\n\005value\030\002 \001(\0132!.apache.rocketmq." +
      "v2.ConsumeStatus:\0028\001\"\327\001\n DescribeGroupAc" +
      "cumulationRequest\022\034\n\017deployment_name\030\001 \001" +
      "(\tH\000\210\001\001\022+\n\005group\030\002 \001(\0132\034.apache.rocketmq" +
      ".v2.Resource\022,\n\006topics\030\003 \003(\0132\034.apache.ro" +
      "cketmq.v2.Resource\022\027\n\nlite_topic\030\004 \001(\tH\001" +
      "\210\001\001B\022\n\020_deployment_nameB\r\n\013_lite_topic\"\315" +
      "\006\n!DescribeGroupAccumulationResponse\022*\n\006" +
      "status\030\001 \001(\0132\032.apache.rocketmq.v2.Status" +
      "\022]\n\014accumulation\030\002 \001(\0132G.apache.rocketmq" +
      ".v2.DescribeGroupAccumulationResponse.Gr" +
      "oupAccumulation\022h\n\022topic_accumulation\030\003 " +
      "\003(\0132L.apache.rocketmq.v2.DescribeGroupAc" +
      "cumulationResponse.TopicAccumulationEntr" +
      "y\022q\n\027lite_topic_accumulation\030\004 \003(\0132P.apa" +
      "che.rocketmq.v2.DescribeGroupAccumulatio" +
      "nResponse.LiteTopicAccumulationEntry\032\263\001\n" +
      "\021GroupAccumulation\022\031\n\021inflight_messages\030" +
      "\001 \001(\003\022\026\n\016ready_messages\030\002 \001(\003\022\024\n\014accumul" +
      "ation\030\003 \001(\003\0225\n\022deliver_delay_time\030\004 \001(\0132" +
      "\031.google.protobuf.Duration\022\036\n\026last_consu" +
      "me_timestamp\030\005 \001(\003\032\201\001\n\026TopicAccumulation" +
      "Entry\022\013\n\003key\030\001 \001(\t\022V\n\005value\030\002 \001(\0132G.apac" +
      "he.rocketmq.v2.DescribeGroupAccumulation" +
      "Response.GroupAccumulation:\0028\001\032\205\001\n\032LiteT" +
      "opicAccumulationEntry\022\013\n\003key\030\001 \001(\t\022V\n\005va" +
      "lue\030\002 \001(\0132G.apache.rocketmq.v2.DescribeG" +
      "roupAccumulationResponse.GroupAccumulati" +
      "on:\0028\001\"\243\001\n\024QueryTimeSpanRequest\022\034\n\017deplo" +
      "yment_name\030\001 \001(\tH\000\210\001\001\022+\n\005group\030\002 \001(\0132\034.a" +
      "pache.rocketmq.v2.Resource\022,\n\006topics\030\003 \003" +
      "(\0132\034.apache.rocketmq.v2.ResourceB\022\n\020_dep" +
      "loyment_name\"\305\002\n\025QueryTimeSpanResponse\022*" +
      "\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.Stat" +
      "us\022U\n\024queue_time_span_list\030\002 \003(\01327.apach" +
      "e.rocketmq.v2.QueryTimeSpanResponse.Queu" +
      "eTimeSpan\032\250\001\n\rQueueTimeSpan\0227\n\rmessage_q" +
      "ueue\030\001 \001(\0132 .apache.rocketmq.v2.MessageQ" +
      "ueue\022\025\n\rmin_timestamp\030\002 \001(\003\022\025\n\rmax_times" +
      "tamp\030\003 \001(\003\022\031\n\021consume_timestamp\030\004 \001(\003\022\025\n" +
      "\rdelay_time_ms\030\005 \001(\003\"\340\001\n\035ListConsumerCon" +
      "nectionRequest\022\034\n\017deployment_name\030\001 \001(\tH" +
      "\000\210\001\001\022+\n\005group\030\002 \001(\0132\034.apache.rocketmq.v2" +
      ".Resource\0220\n\005topic\030\003 \001(\0132\034.apache.rocket" +
      "mq.v2.ResourceH\001\210\001\001\022\026\n\tliteTopic\030\004 \001(\tH\002" +
      "\210\001\001B\022\n\020_deployment_nameB\010\n\006_topicB\014\n\n_li" +
      "teTopic\"\201\001\n\036ListConsumerConnectionRespon" +
      "se\022*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2." +
      "Status\0223\n\013client_info\030\002 \003(\0132\036.apache.roc" +
      "ketmq.v2.ClientInfo\"\332\001\n\027ResetGroupOffset" +
      "Request\022\034\n\017deployment_name\030\001 \001(\tH\000\210\001\001\022+\n" +
      "\005group\030\002 \001(\0132\034.apache.rocketmq.v2.Resour" +
      "ce\022+\n\005topic\030\003 \001(\0132\034.apache.rocketmq.v2.R" +
      "esource\0223\n\017reset_timestamp\030\004 \001(\0132\032.googl" +
      "e.protobuf.TimestampB\022\n\020_deployment_name" +
      "\"F\n\030ResetGroupOffsetResponse\022*\n\006status\030\001" +
      " \001(\0132\032.apache.rocketmq.v2.Status\"\234\004\n\022Lis" +
      "tMessageRequest\022\034\n\017deployment_name\030\001 \001(\t" +
      "H\001\210\001\001\022+\n\005topic\030\002 \001(\0132\034.apache.rocketmq.v" +
      "2.Resource\022\030\n\020max_message_nums\030\003 \001(\005\0223\n\017" +
      "begin_timestamp\030\004 \001(\0132\032.google.protobuf." +
      "Timestamp\0221\n\rend_timestamp\030\005 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\024\n\nmessage_id\030\006 \001(\t" +
      "H\000\022\025\n\013message_key\030\007 \001(\tH\000\022\026\n\014subscriptio" +
      "n\030\010 \001(\tH\000\022\024\n\nlite_topic\030\016 \001(\tH\000\022\026\n\tscrol" +
      "l_id\030\t \001(\tH\002\210\001\001\022\025\n\010page_num\030\n \001(\005H\003\210\001\001\022\026" +
      "\n\tpage_size\030\013 \001(\005H\004\210\001\001\022\030\n\013broker_name\030\014 " +
      "\001(\tH\005\210\001\001\022\025\n\010queue_id\030\r \001(\005H\006\210\001\001B\014\n\nsearc" +
      "h_keyB\022\n\020_deployment_nameB\014\n\n_scroll_idB" +
      "\013\n\t_page_numB\014\n\n_page_sizeB\016\n\014_broker_na" +
      "meB\013\n\t_queue_id\"\203\001\n\023ListMessageResponse\022" +
      "*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.Sta" +
      "tus\022-\n\010messages\030\002 \003(\0132\033.apache.rocketmq." +
      "v2.Message\022\021\n\tscroll_id\030\003 \001(\t\"\220\001\n\034PrintT" +
      "hreadStackTraceRequest\022\034\n\017deployment_nam" +
      "e\030\001 \001(\tH\000\210\001\001\022\021\n\tclient_id\030\002 \001(\t\022+\n\005group" +
      "\030\003 \001(\0132\034.apache.rocketmq.v2.ResourceB\022\n\020" +
      "_deployment_name\"\203\001\n\035PrintThreadStackTra" +
      "ceResponse\022*\n\006status\030\001 \001(\0132\032.apache.rock" +
      "etmq.v2.Status\022\037\n\022thread_stack_trace\030\002 \001" +
      "(\tH\000\210\001\001B\025\n\023_thread_stack_trace\"\311\001\n\024Verif" +
      "yMessageRequest\022\034\n\017deployment_name\030\001 \001(\t" +
      "H\000\210\001\001\022\021\n\tclient_id\030\002 \001(\t\022+\n\005group\030\003 \001(\0132" +
      "\034.apache.rocketmq.v2.Resource\022+\n\005topic\030\004" +
      " \001(\0132\034.apache.rocketmq.v2.Resource\022\022\n\nme" +
      "ssage_id\030\005 \001(\tB\022\n\020_deployment_name\"C\n\025Ve" +
      "rifyMessageResponse\022*\n\006status\030\001 \001(\0132\032.ap" +
      "ache.rocketmq.v2.Status\"\243\004\n\027AdminSendMes" +
      "sageRequest\022\034\n\017deployment_name\030\001 \001(\tH\000\210\001" +
      "\001\022+\n\005topic\030\002 \001(\0132\034.apache.rocketmq.v2.Re" +
      "source\022\020\n\003tag\030\003 \001(\tH\001\210\001\001\022\020\n\003key\030\004 \001(\tH\002\210" +
      "\001\001\022\014\n\004body\030\005 \001(\014\022X\n\017user_properties\030\006 \003(" +
      "\0132?.apache.rocketmq.v2.AdminSendMessageR" +
      "equest.UserPropertiesEntry\022D\n\021system_pro" +
      "perties\030\007 \001(\0132$.apache.rocketmq.v2.Syste" +
      "mPropertiesH\003\210\001\001\022J\n\010ext_info\030\010 \003(\01328.apa" +
      "che.rocketmq.v2.AdminSendMessageRequest." +
      "ExtInfoEntry\0325\n\023UserPropertiesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032.\n\014ExtInfoEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\022\n\020_" +
      "deployment_nameB\006\n\004_tagB\006\n\004_keyB\024\n\022_syst" +
      "em_properties\"Z\n\030AdminSendMessageRespons" +
      "e\022*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.S" +
      "tatus\022\022\n\nmessage_id\030\002 \001(\t\"\221\001\n\035GetConsume" +
      "rRunningInfoRequest\022\034\n\017deployment_name\030\001" +
      " \001(\tH\000\210\001\001\022+\n\005group\030\002 \001(\0132\034.apache.rocket" +
      "mq.v2.Resource\022\021\n\tclient_id\030\003 \001(\tB\022\n\020_de" +
      "ployment_name\"\224\001\n\036GetConsumerRunningInfo" +
      "Response\022*\n\006status\030\001 \001(\0132\032.apache.rocket" +
      "mq.v2.Status\022F\n\025consumer_running_info\030\002 " +
      "\001(\0132\'.apache.rocketmq.v2.ConsumerRunning" +
      "Info\"\306\002\n\024GetTopicRouteRequest\022\034\n\017deploym" +
      "ent_name\030\001 \001(\tH\000\210\001\001\022+\n\005topic\030\002 \001(\0132\034.apa" +
      "che.rocketmq.v2.Resource\022J\n\014network_type" +
      "\030\003 \001(\01624.apache.rocketmq.v2.GetTopicRout" +
      "eRequest.NetworkType\022\025\n\rprotocol_type\030\004 " +
      "\001(\t\022\033\n\023stream_request_type\030\005 \001(\010\022\026\n\016clie" +
      "nt_address\030\006 \001(\t\"7\n\013NetworkType\022\014\n\010INTER" +
      "NAL\020\000\022\014\n\010INTERNET\020\001\022\014\n\010INTRANET\020\002B\022\n\020_de" +
      "ployment_name\"]\n\025GetTopicRouteResponse\022*" +
      "\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.Stat" +
      "us\022\030\n\020topic_route_data\030\002 \001(\t\"\035\n\033GetProxy" +
      "RuntimeStatsRequest\"\313\001\n\034GetProxyRuntimeS" +
      "tatsResponse\022*\n\006status\030\001 \001(\0132\032.apache.ro" +
      "cketmq.v2.Status\022\022\n\nproxy_name\030\002 \001(\t\022\017\n\007" +
      "version\030\003 \001(\t\022\016\n\006in_tps\030\004 \001(\001\022\017\n\007out_tps" +
      "\030\005 \001(\001\022\023\n\013connections\030\006 \001(\003\022\021\n\tproducers" +
      "\030\007 \001(\003\022\021\n\tconsumers\030\010 \001(\003*c\n\014MessageMode" +
      "l\022\035\n\031MESSAGE_MODEL_UNSPECIFIED\020\000\022\016\n\nCLUS" +
      "TERING\020\001\022\020\n\014BROADCASTING\020\002\022\022\n\016LITE_SELEC" +
      "TIVE\020\0032\340\016\n\005Admin\022i\n\016ChangeLogLevel\022).apa" +
      "che.rocketmq.v2.ChangeLogLevelRequest\032*." +
      "apache.rocketmq.v2.ChangeLogLevelRespons" +
      "e\"\000\022x\n\023DescribeTopicStatus\022..apache.rock" +
      "etmq.v2.DescribeTopicStatusRequest\032/.apa" +
      "che.rocketmq.v2.DescribeTopicStatusRespo" +
      "nse\"\000\022o\n\020ListSubscription\022+.apache.rocke" +
      "tmq.v2.ListSubscriptionRequest\032,.apache." +
      "rocketmq.v2.ListSubscriptionResponse\"\000\022{" +
      "\n\024DescribeSubscription\022/.apache.rocketmq" +
      ".v2.DescribeSubscriptionRequest\0320.apache" +
      ".rocketmq.v2.DescribeSubscriptionRespons" +
      "e\"\000\022u\n\022DeleteSubscription\022-.apache.rocke" +
      "tmq.v2.DeleteSubscriptionRequest\032..apach" +
      "e.rocketmq.v2.DeleteSubscriptionResponse" +
      "\"\000\022\212\001\n\031DescribeGroupAccumulation\0224.apach" +
      "e.rocketmq.v2.DescribeGroupAccumulationR" +
      "equest\0325.apache.rocketmq.v2.DescribeGrou" +
      "pAccumulationResponse\"\000\022\201\001\n\026ListConsumer" +
      "Connection\0221.apache.rocketmq.v2.ListCons" +
      "umerConnectionRequest\0322.apache.rocketmq." +
      "v2.ListConsumerConnectionResponse\"\000\022o\n\020R" +
      "esetGroupOffset\022+.apache.rocketmq.v2.Res" +
      "etGroupOffsetRequest\032,.apache.rocketmq.v" +
      "2.ResetGroupOffsetResponse\"\000\022a\n\014QueryMes" +
      "sage\022&.apache.rocketmq.v2.ListMessageReq" +
      "uest\032\'.apache.rocketmq.v2.ListMessageRes" +
      "ponse\"\000\022~\n\025PrintThreadStackTrace\0220.apach" +
      "e.rocketmq.v2.PrintThreadStackTraceReque" +
      "st\0321.apache.rocketmq.v2.PrintThreadStack" +
      "TraceResponse\"\000\022f\n\rVerifyMessage\022(.apach" +
      "e.rocketmq.v2.VerifyMessageRequest\032).apa" +
      "che.rocketmq.v2.VerifyMessageResponse\"\000\022" +
      "o\n\020AdminSendMessage\022+.apache.rocketmq.v2" +
      ".AdminSendMessageRequest\032,.apache.rocket" +
      "mq.v2.AdminSendMessageResponse\"\000\022\201\001\n\026Get" +
      "ConsumerRunningInfo\0221.apache.rocketmq.v2" +
      ".GetConsumerRunningInfoRequest\0322.apache." +
      "rocketmq.v2.GetConsumerRunningInfoRespon" +
      "se\"\000\022f\n\rGetTopicRoute\022(.apache.rocketmq." +
      "v2.GetTopicRouteRequest\032).apache.rocketm" +
      "q.v2.GetTopicRouteResponse\"\000\022f\n\rQueryTim" +
      "eSpan\022(.apache.rocketmq.v2.QueryTimeSpan" +
      "Request\032).apache.rocketmq.v2.QueryTimeSp" +
      "anResponse\"\000\022{\n\024GetProxyRuntimeStats\022/.a" +
      "pache.rocketmq.v2.GetProxyRuntimeStatsRe" +
      "quest\0320.apache.rocketmq.v2.GetProxyRunti" +
      "meStatsResponse\"\000B=\n\022apache.rocketmq.v2B" +
      "\007MQAdminP\001\240\001\001\330\001\001\370\001\001\252\002\022Apache.Rocketmq.V2" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          apache.rocketmq.v2.MQDomain.getDescriptor(),
        });
    internal_static_apache_rocketmq_v2_ChangeLogLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apache_rocketmq_v2_ChangeLogLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeLogLevelRequest_descriptor,
        new java.lang.String[] { "Level", });
    internal_static_apache_rocketmq_v2_ChangeLogLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apache_rocketmq_v2_ChangeLogLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeLogLevelResponse_descriptor,
        new java.lang.String[] { "Remark", });
    internal_static_apache_rocketmq_v2_DescribeTopicStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apache_rocketmq_v2_DescribeTopicStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeTopicStatusRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "DeploymentName", });
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_descriptor,
        new java.lang.String[] { "Status", "TopicMessageType", "Description", "CreateTimestamp", "Tags", "Description", "CreateTimestamp", });
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_TagsEntry_descriptor =
      internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeTopicStatusResponse_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_ListSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apache_rocketmq_v2_ListSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListSubscriptionRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "Group", "DeploymentName", "Topic", "Group", });
    internal_static_apache_rocketmq_v2_SubscriptionInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apache_rocketmq_v2_SubscriptionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SubscriptionInfo_descriptor,
        new java.lang.String[] { "Group", "Topic", "Expression", "Online", "LastUpdateTimestamp", "MessageModel", "SubscriptionConsistency", });
    internal_static_apache_rocketmq_v2_ListSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_apache_rocketmq_v2_ListSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListSubscriptionResponse_descriptor,
        new java.lang.String[] { "Status", "SubscriptionInfo", });
    internal_static_apache_rocketmq_v2_DescribeSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_apache_rocketmq_v2_DescribeSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeSubscriptionRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "Group", "DeploymentName", "Topic", "Group", });
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_descriptor,
        new java.lang.String[] { "Status", "ClientSubscriptionInfo", });
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_ClientSubscriptionInfo_descriptor =
      internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_ClientSubscriptionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeSubscriptionResponse_ClientSubscriptionInfo_descriptor,
        new java.lang.String[] { "ClientInfo", "SubscriptionInfo", });
    internal_static_apache_rocketmq_v2_DeleteSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_apache_rocketmq_v2_DeleteSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DeleteSubscriptionRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "Group", "Expression", "DeploymentName", });
    internal_static_apache_rocketmq_v2_DeleteSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_apache_rocketmq_v2_DeleteSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DeleteSubscriptionResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_apache_rocketmq_v2_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ClientInfo_descriptor,
        new java.lang.String[] { "ClientId", "Version", "Language", "Hostname", "EgressIp", "MessageModel", });
    internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_apache_rocketmq_v2_MessageQueueItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_MessageQueueItem_descriptor,
        new java.lang.String[] { "MessageQueue", "ProcessQueueInfo", });
    internal_static_apache_rocketmq_v2_ProcessQueueInfo_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_apache_rocketmq_v2_ProcessQueueInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ProcessQueueInfo_descriptor,
        new java.lang.String[] { "CommitOffset", "CachedMsgMinOffset", "CachedMsgMaxOffset", "CachedMsgCount", "CachedMsgSizeInMib", "TransactionMsgMinOffset", "TransactionMsgMaxOffset", "TransactionMsgCount", "Locked", "TryUnlockTimes", "LastLockTimestamp", "Dropped", "LastPullTimestamp", "LastConsumeTimestamp", });
    internal_static_apache_rocketmq_v2_ConsumeStatus_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_apache_rocketmq_v2_ConsumeStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ConsumeStatus_descriptor,
        new java.lang.String[] { "ReceiveRt", "ReceiveTps", "ConsumeRt", "ConsumeOkTps", "ConsumeFailedTps", "ConsumeFailedMsgs", });
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor,
        new java.lang.String[] { "Properties", "Subscriptions", "MessageQueueTable", "ConsumeStatusTable", });
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_PropertiesEntry_descriptor =
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ConsumerRunningInfo_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_SubscriptionsEntry_descriptor =
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor.getNestedTypes().get(1);
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_SubscriptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ConsumerRunningInfo_SubscriptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_ConsumeStatusTableEntry_descriptor =
      internal_static_apache_rocketmq_v2_ConsumerRunningInfo_descriptor.getNestedTypes().get(2);
    internal_static_apache_rocketmq_v2_ConsumerRunningInfo_ConsumeStatusTableEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ConsumerRunningInfo_ConsumeStatusTableEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeGroupAccumulationRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Group", "Topics", "LiteTopic", "DeploymentName", "LiteTopic", });
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor,
        new java.lang.String[] { "Status", "Accumulation", "TopicAccumulation", "LiteTopicAccumulation", });
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_GroupAccumulation_descriptor =
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_GroupAccumulation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_GroupAccumulation_descriptor,
        new java.lang.String[] { "InflightMessages", "ReadyMessages", "Accumulation", "DeliverDelayTime", "LastConsumeTimestamp", });
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_TopicAccumulationEntry_descriptor =
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor.getNestedTypes().get(1);
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_TopicAccumulationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_TopicAccumulationEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_LiteTopicAccumulationEntry_descriptor =
      internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_descriptor.getNestedTypes().get(2);
    internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_LiteTopicAccumulationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_DescribeGroupAccumulationResponse_LiteTopicAccumulationEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_QueryTimeSpanRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_apache_rocketmq_v2_QueryTimeSpanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryTimeSpanRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Group", "Topics", "DeploymentName", });
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_descriptor,
        new java.lang.String[] { "Status", "QueueTimeSpanList", });
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_QueueTimeSpan_descriptor =
      internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_QueueTimeSpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryTimeSpanResponse_QueueTimeSpan_descriptor,
        new java.lang.String[] { "MessageQueue", "MinTimestamp", "MaxTimestamp", "ConsumeTimestamp", "DelayTimeMs", });
    internal_static_apache_rocketmq_v2_ListConsumerConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_apache_rocketmq_v2_ListConsumerConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListConsumerConnectionRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Group", "Topic", "LiteTopic", "DeploymentName", "Topic", "LiteTopic", });
    internal_static_apache_rocketmq_v2_ListConsumerConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_apache_rocketmq_v2_ListConsumerConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListConsumerConnectionResponse_descriptor,
        new java.lang.String[] { "Status", "ClientInfo", });
    internal_static_apache_rocketmq_v2_ResetGroupOffsetRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_apache_rocketmq_v2_ResetGroupOffsetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ResetGroupOffsetRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Group", "Topic", "ResetTimestamp", "DeploymentName", });
    internal_static_apache_rocketmq_v2_ResetGroupOffsetResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_apache_rocketmq_v2_ResetGroupOffsetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ResetGroupOffsetResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_ListMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_apache_rocketmq_v2_ListMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListMessageRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "MaxMessageNums", "BeginTimestamp", "EndTimestamp", "MessageId", "MessageKey", "Subscription", "LiteTopic", "ScrollId", "PageNum", "PageSize", "BrokerName", "QueueId", "SearchKey", "DeploymentName", "ScrollId", "PageNum", "PageSize", "BrokerName", "QueueId", });
    internal_static_apache_rocketmq_v2_ListMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_apache_rocketmq_v2_ListMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ListMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Messages", "ScrollId", });
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_PrintThreadStackTraceRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "ClientId", "Group", "DeploymentName", });
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_PrintThreadStackTraceResponse_descriptor,
        new java.lang.String[] { "Status", "ThreadStackTrace", "ThreadStackTrace", });
    internal_static_apache_rocketmq_v2_VerifyMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_apache_rocketmq_v2_VerifyMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "ClientId", "Group", "Topic", "MessageId", "DeploymentName", });
    internal_static_apache_rocketmq_v2_VerifyMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_apache_rocketmq_v2_VerifyMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AdminSendMessageRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "Tag", "Key", "Body", "UserProperties", "SystemProperties", "ExtInfo", "DeploymentName", "Tag", "Key", "SystemProperties", });
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_UserPropertiesEntry_descriptor =
      internal_static_apache_rocketmq_v2_AdminSendMessageRequest_descriptor.getNestedTypes().get(0);
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_UserPropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AdminSendMessageRequest_UserPropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_ExtInfoEntry_descriptor =
      internal_static_apache_rocketmq_v2_AdminSendMessageRequest_descriptor.getNestedTypes().get(1);
    internal_static_apache_rocketmq_v2_AdminSendMessageRequest_ExtInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AdminSendMessageRequest_ExtInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apache_rocketmq_v2_AdminSendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_apache_rocketmq_v2_AdminSendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AdminSendMessageResponse_descriptor,
        new java.lang.String[] { "Status", "MessageId", });
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetConsumerRunningInfoRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Group", "ClientId", "DeploymentName", });
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_apache_rocketmq_v2_GetConsumerRunningInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetConsumerRunningInfoResponse_descriptor,
        new java.lang.String[] { "Status", "ConsumerRunningInfo", });
    internal_static_apache_rocketmq_v2_GetTopicRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_apache_rocketmq_v2_GetTopicRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetTopicRouteRequest_descriptor,
        new java.lang.String[] { "DeploymentName", "Topic", "NetworkType", "ProtocolType", "StreamRequestType", "ClientAddress", "DeploymentName", });
    internal_static_apache_rocketmq_v2_GetTopicRouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_apache_rocketmq_v2_GetTopicRouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetTopicRouteResponse_descriptor,
        new java.lang.String[] { "Status", "TopicRouteData", });
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_GetProxyRuntimeStatsResponse_descriptor,
        new java.lang.String[] { "Status", "ProxyName", "Version", "InTps", "OutTps", "Connections", "Producers", "Consumers", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    apache.rocketmq.v2.MQDomain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
