// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.OffsetOption}
 */
public final class OffsetOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.OffsetOption)
    OffsetOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OffsetOption.newBuilder() to construct.
  private OffsetOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OffsetOption() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OffsetOption();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OffsetOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
            offsetTypeCase_ = 1;
            offsetType_ = rawValue;
            break;
          }
          case 16: {
            offsetType_ = input.readInt64();
            offsetTypeCase_ = 2;
            break;
          }
          case 24: {
            offsetType_ = input.readInt64();
            offsetTypeCase_ = 3;
            break;
          }
          case 32: {
            offsetType_ = input.readInt64();
            offsetTypeCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_OffsetOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_OffsetOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.OffsetOption.class, apache.rocketmq.v2.OffsetOption.Builder.class);
  }

  /**
   * Protobuf enum {@code apache.rocketmq.v2.OffsetOption.Policy}
   */
  public enum Policy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAST = 0;</code>
     */
    LAST(0),
    /**
     * <code>MIN = 1;</code>
     */
    MIN(1),
    /**
     * <code>MAX = 2;</code>
     */
    MAX(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LAST = 0;</code>
     */
    public static final int LAST_VALUE = 0;
    /**
     * <code>MIN = 1;</code>
     */
    public static final int MIN_VALUE = 1;
    /**
     * <code>MAX = 2;</code>
     */
    public static final int MAX_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Policy valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Policy forNumber(int value) {
      switch (value) {
        case 0: return LAST;
        case 1: return MIN;
        case 2: return MAX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Policy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Policy> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Policy>() {
            public Policy findValueByNumber(int number) {
              return Policy.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return apache.rocketmq.v2.OffsetOption.getDescriptor().getEnumTypes().get(0);
    }

    private static final Policy[] VALUES = values();

    public static Policy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Policy(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:apache.rocketmq.v2.OffsetOption.Policy)
  }

  private int offsetTypeCase_ = 0;
  private java.lang.Object offsetType_;
  public enum OffsetTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POLICY(1),
    OFFSET(2),
    TAIL_N(3),
    TIMESTAMP(4),
    OFFSETTYPE_NOT_SET(0);
    private final int value;
    private OffsetTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OffsetTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static OffsetTypeCase forNumber(int value) {
      switch (value) {
        case 1: return POLICY;
        case 2: return OFFSET;
        case 3: return TAIL_N;
        case 4: return TIMESTAMP;
        case 0: return OFFSETTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OffsetTypeCase
  getOffsetTypeCase() {
    return OffsetTypeCase.forNumber(
        offsetTypeCase_);
  }

  public static final int POLICY_FIELD_NUMBER = 1;
  /**
   * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
   * @return Whether the policy field is set.
   */
  public boolean hasPolicy() {
    return offsetTypeCase_ == 1;
  }
  /**
   * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
   * @return The enum numeric value on the wire for policy.
   */
  public int getPolicyValue() {
    if (offsetTypeCase_ == 1) {
      return (java.lang.Integer) offsetType_;
    }
    return 0;
  }
  /**
   * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
   * @return The policy.
   */
  public apache.rocketmq.v2.OffsetOption.Policy getPolicy() {
    if (offsetTypeCase_ == 1) {
      @SuppressWarnings("deprecation")
      apache.rocketmq.v2.OffsetOption.Policy result = apache.rocketmq.v2.OffsetOption.Policy.valueOf(
          (java.lang.Integer) offsetType_);
      return result == null ? apache.rocketmq.v2.OffsetOption.Policy.UNRECOGNIZED : result;
    }
    return apache.rocketmq.v2.OffsetOption.Policy.LAST;
  }

  public static final int OFFSET_FIELD_NUMBER = 2;
  /**
   * <code>int64 offset = 2;</code>
   * @return Whether the offset field is set.
   */
  @java.lang.Override
  public boolean hasOffset() {
    return offsetTypeCase_ == 2;
  }
  /**
   * <code>int64 offset = 2;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    if (offsetTypeCase_ == 2) {
      return (java.lang.Long) offsetType_;
    }
    return 0L;
  }

  public static final int TAIL_N_FIELD_NUMBER = 3;
  /**
   * <code>int64 tail_n = 3;</code>
   * @return Whether the tailN field is set.
   */
  @java.lang.Override
  public boolean hasTailN() {
    return offsetTypeCase_ == 3;
  }
  /**
   * <code>int64 tail_n = 3;</code>
   * @return The tailN.
   */
  @java.lang.Override
  public long getTailN() {
    if (offsetTypeCase_ == 3) {
      return (java.lang.Long) offsetType_;
    }
    return 0L;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  /**
   * <code>int64 timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return offsetTypeCase_ == 4;
  }
  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    if (offsetTypeCase_ == 4) {
      return (java.lang.Long) offsetType_;
    }
    return 0L;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (offsetTypeCase_ == 1) {
      output.writeEnum(1, ((java.lang.Integer) offsetType_));
    }
    if (offsetTypeCase_ == 2) {
      output.writeInt64(
          2, (long)((java.lang.Long) offsetType_));
    }
    if (offsetTypeCase_ == 3) {
      output.writeInt64(
          3, (long)((java.lang.Long) offsetType_));
    }
    if (offsetTypeCase_ == 4) {
      output.writeInt64(
          4, (long)((java.lang.Long) offsetType_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (offsetTypeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ((java.lang.Integer) offsetType_));
    }
    if (offsetTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            2, (long)((java.lang.Long) offsetType_));
    }
    if (offsetTypeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            3, (long)((java.lang.Long) offsetType_));
    }
    if (offsetTypeCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            4, (long)((java.lang.Long) offsetType_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.OffsetOption)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.OffsetOption other = (apache.rocketmq.v2.OffsetOption) obj;

    if (!getOffsetTypeCase().equals(other.getOffsetTypeCase())) return false;
    switch (offsetTypeCase_) {
      case 1:
        if (getPolicyValue()
            != other.getPolicyValue()) return false;
        break;
      case 2:
        if (getOffset()
            != other.getOffset()) return false;
        break;
      case 3:
        if (getTailN()
            != other.getTailN()) return false;
        break;
      case 4:
        if (getTimestamp()
            != other.getTimestamp()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (offsetTypeCase_) {
      case 1:
        hash = (37 * hash) + POLICY_FIELD_NUMBER;
        hash = (53 * hash) + getPolicyValue();
        break;
      case 2:
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOffset());
        break;
      case 3:
        hash = (37 * hash) + TAIL_N_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTailN());
        break;
      case 4:
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.OffsetOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.OffsetOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.OffsetOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.OffsetOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.OffsetOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.OffsetOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.OffsetOption)
      apache.rocketmq.v2.OffsetOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_OffsetOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_OffsetOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.OffsetOption.class, apache.rocketmq.v2.OffsetOption.Builder.class);
    }

    // Construct using apache.rocketmq.v2.OffsetOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      offsetTypeCase_ = 0;
      offsetType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_OffsetOption_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.OffsetOption getDefaultInstanceForType() {
      return apache.rocketmq.v2.OffsetOption.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.OffsetOption build() {
      apache.rocketmq.v2.OffsetOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.OffsetOption buildPartial() {
      apache.rocketmq.v2.OffsetOption result = new apache.rocketmq.v2.OffsetOption(this);
      if (offsetTypeCase_ == 1) {
        result.offsetType_ = offsetType_;
      }
      if (offsetTypeCase_ == 2) {
        result.offsetType_ = offsetType_;
      }
      if (offsetTypeCase_ == 3) {
        result.offsetType_ = offsetType_;
      }
      if (offsetTypeCase_ == 4) {
        result.offsetType_ = offsetType_;
      }
      result.offsetTypeCase_ = offsetTypeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.OffsetOption) {
        return mergeFrom((apache.rocketmq.v2.OffsetOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.OffsetOption other) {
      if (other == apache.rocketmq.v2.OffsetOption.getDefaultInstance()) return this;
      switch (other.getOffsetTypeCase()) {
        case POLICY: {
          setPolicyValue(other.getPolicyValue());
          break;
        }
        case OFFSET: {
          setOffset(other.getOffset());
          break;
        }
        case TAIL_N: {
          setTailN(other.getTailN());
          break;
        }
        case TIMESTAMP: {
          setTimestamp(other.getTimestamp());
          break;
        }
        case OFFSETTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.OffsetOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.OffsetOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int offsetTypeCase_ = 0;
    private java.lang.Object offsetType_;
    public OffsetTypeCase
        getOffsetTypeCase() {
      return OffsetTypeCase.forNumber(
          offsetTypeCase_);
    }

    public Builder clearOffsetType() {
      offsetTypeCase_ = 0;
      offsetType_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @return Whether the policy field is set.
     */
    @java.lang.Override
    public boolean hasPolicy() {
      return offsetTypeCase_ == 1;
    }
    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @return The enum numeric value on the wire for policy.
     */
    @java.lang.Override
    public int getPolicyValue() {
      if (offsetTypeCase_ == 1) {
        return ((java.lang.Integer) offsetType_).intValue();
      }
      return 0;
    }
    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @param value The enum numeric value on the wire for policy to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyValue(int value) {
      offsetTypeCase_ = 1;
      offsetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @return The policy.
     */
    @java.lang.Override
    public apache.rocketmq.v2.OffsetOption.Policy getPolicy() {
      if (offsetTypeCase_ == 1) {
        @SuppressWarnings("deprecation")
        apache.rocketmq.v2.OffsetOption.Policy result = apache.rocketmq.v2.OffsetOption.Policy.valueOf(
            (java.lang.Integer) offsetType_);
        return result == null ? apache.rocketmq.v2.OffsetOption.Policy.UNRECOGNIZED : result;
      }
      return apache.rocketmq.v2.OffsetOption.Policy.LAST;
    }
    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @param value The policy to set.
     * @return This builder for chaining.
     */
    public Builder setPolicy(apache.rocketmq.v2.OffsetOption.Policy value) {
      if (value == null) {
        throw new NullPointerException();
      }
      offsetTypeCase_ = 1;
      offsetType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.OffsetOption.Policy policy = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPolicy() {
      if (offsetTypeCase_ == 1) {
        offsetTypeCase_ = 0;
        offsetType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 offset = 2;</code>
     * @return Whether the offset field is set.
     */
    public boolean hasOffset() {
      return offsetTypeCase_ == 2;
    }
    /**
     * <code>int64 offset = 2;</code>
     * @return The offset.
     */
    public long getOffset() {
      if (offsetTypeCase_ == 2) {
        return (java.lang.Long) offsetType_;
      }
      return 0L;
    }
    /**
     * <code>int64 offset = 2;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      offsetTypeCase_ = 2;
      offsetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      if (offsetTypeCase_ == 2) {
        offsetTypeCase_ = 0;
        offsetType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 tail_n = 3;</code>
     * @return Whether the tailN field is set.
     */
    public boolean hasTailN() {
      return offsetTypeCase_ == 3;
    }
    /**
     * <code>int64 tail_n = 3;</code>
     * @return The tailN.
     */
    public long getTailN() {
      if (offsetTypeCase_ == 3) {
        return (java.lang.Long) offsetType_;
      }
      return 0L;
    }
    /**
     * <code>int64 tail_n = 3;</code>
     * @param value The tailN to set.
     * @return This builder for chaining.
     */
    public Builder setTailN(long value) {
      offsetTypeCase_ = 3;
      offsetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tail_n = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTailN() {
      if (offsetTypeCase_ == 3) {
        offsetTypeCase_ = 0;
        offsetType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return offsetTypeCase_ == 4;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      if (offsetTypeCase_ == 4) {
        return (java.lang.Long) offsetType_;
      }
      return 0L;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      offsetTypeCase_ = 4;
      offsetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      if (offsetTypeCase_ == 4) {
        offsetTypeCase_ = 0;
        offsetType_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.OffsetOption)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.OffsetOption)
  private static final apache.rocketmq.v2.OffsetOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.OffsetOption();
  }

  public static apache.rocketmq.v2.OffsetOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OffsetOption>
      PARSER = new com.google.protobuf.AbstractParser<OffsetOption>() {
    @java.lang.Override
    public OffsetOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OffsetOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OffsetOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OffsetOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.OffsetOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

