// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface QueryTimeSpanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.QueryTimeSpanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  apache.rocketmq.v2.Status getStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>repeated .apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan queue_time_span_list = 2;</code>
   */
  java.util.List<apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan> 
      getQueueTimeSpanListList();
  /**
   * <code>repeated .apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan queue_time_span_list = 2;</code>
   */
  apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan getQueueTimeSpanList(int index);
  /**
   * <code>repeated .apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan queue_time_span_list = 2;</code>
   */
  int getQueueTimeSpanListCount();
  /**
   * <code>repeated .apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan queue_time_span_list = 2;</code>
   */
  java.util.List<? extends apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpanOrBuilder> 
      getQueueTimeSpanListOrBuilderList();
  /**
   * <code>repeated .apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpan queue_time_span_list = 2;</code>
   */
  apache.rocketmq.v2.QueryTimeSpanResponse.QueueTimeSpanOrBuilder getQueueTimeSpanListOrBuilder(
      int index);
}
