// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.ReceiveMessageResponse}
 */
public final class ReceiveMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.ReceiveMessageResponse)
    ReceiveMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReceiveMessageResponse.newBuilder() to construct.
  private ReceiveMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReceiveMessageResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReceiveMessageResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReceiveMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.Status.Builder subBuilder = null;
            if (contentCase_ == 1) {
              subBuilder = ((apache.rocketmq.v2.Status) content_).toBuilder();
            }
            content_ =
                input.readMessage(apache.rocketmq.v2.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.Status) content_);
              content_ = subBuilder.buildPartial();
            }
            contentCase_ = 1;
            break;
          }
          case 18: {
            apache.rocketmq.v2.Message.Builder subBuilder = null;
            if (contentCase_ == 2) {
              subBuilder = ((apache.rocketmq.v2.Message) content_).toBuilder();
            }
            content_ =
                input.readMessage(apache.rocketmq.v2.Message.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.Message) content_);
              content_ = subBuilder.buildPartial();
            }
            contentCase_ = 2;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (contentCase_ == 3) {
              subBuilder = ((com.google.protobuf.Timestamp) content_).toBuilder();
            }
            content_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) content_);
              content_ = subBuilder.buildPartial();
            }
            contentCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.ReceiveMessageResponse.class, apache.rocketmq.v2.ReceiveMessageResponse.Builder.class);
  }

  private int contentCase_ = 0;
  private java.lang.Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STATUS(1),
    MESSAGE(2),
    DELIVERY_TIMESTAMP(3),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 1: return STATUS;
        case 2: return MESSAGE;
        case 3: return DELIVERY_TIMESTAMP;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return contentCase_ == 1;
  }
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Status getStatus() {
    if (contentCase_ == 1) {
       return (apache.rocketmq.v2.Status) content_;
    }
    return apache.rocketmq.v2.Status.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
    if (contentCase_ == 1) {
       return (apache.rocketmq.v2.Status) content_;
    }
    return apache.rocketmq.v2.Status.getDefaultInstance();
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  /**
   * <code>.apache.rocketmq.v2.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return contentCase_ == 2;
  }
  /**
   * <code>.apache.rocketmq.v2.Message message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Message getMessage() {
    if (contentCase_ == 2) {
       return (apache.rocketmq.v2.Message) content_;
    }
    return apache.rocketmq.v2.Message.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v2.Message message = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageOrBuilder getMessageOrBuilder() {
    if (contentCase_ == 2) {
       return (apache.rocketmq.v2.Message) content_;
    }
    return apache.rocketmq.v2.Message.getDefaultInstance();
  }

  public static final int DELIVERY_TIMESTAMP_FIELD_NUMBER = 3;
  /**
   * <pre>
   * The timestamp that brokers start to deliver status line or message.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   * @return Whether the deliveryTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasDeliveryTimestamp() {
    return contentCase_ == 3;
  }
  /**
   * <pre>
   * The timestamp that brokers start to deliver status line or message.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   * @return The deliveryTimestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeliveryTimestamp() {
    if (contentCase_ == 3) {
       return (com.google.protobuf.Timestamp) content_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <pre>
   * The timestamp that brokers start to deliver status line or message.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDeliveryTimestampOrBuilder() {
    if (contentCase_ == 3) {
       return (com.google.protobuf.Timestamp) content_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (contentCase_ == 1) {
      output.writeMessage(1, (apache.rocketmq.v2.Status) content_);
    }
    if (contentCase_ == 2) {
      output.writeMessage(2, (apache.rocketmq.v2.Message) content_);
    }
    if (contentCase_ == 3) {
      output.writeMessage(3, (com.google.protobuf.Timestamp) content_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (contentCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (apache.rocketmq.v2.Status) content_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (apache.rocketmq.v2.Message) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.protobuf.Timestamp) content_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.ReceiveMessageResponse)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.ReceiveMessageResponse other = (apache.rocketmq.v2.ReceiveMessageResponse) obj;

    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 1:
        if (!getStatus()
            .equals(other.getStatus())) return false;
        break;
      case 2:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 3:
        if (!getDeliveryTimestamp()
            .equals(other.getDeliveryTimestamp())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (contentCase_) {
      case 1:
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
        break;
      case 2:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DELIVERY_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getDeliveryTimestamp().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.ReceiveMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.ReceiveMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.ReceiveMessageResponse)
      apache.rocketmq.v2.ReceiveMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.ReceiveMessageResponse.class, apache.rocketmq.v2.ReceiveMessageResponse.Builder.class);
    }

    // Construct using apache.rocketmq.v2.ReceiveMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstanceForType() {
      return apache.rocketmq.v2.ReceiveMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse build() {
      apache.rocketmq.v2.ReceiveMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse buildPartial() {
      apache.rocketmq.v2.ReceiveMessageResponse result = new apache.rocketmq.v2.ReceiveMessageResponse(this);
      if (contentCase_ == 1) {
        if (statusBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = statusBuilder_.build();
        }
      }
      if (contentCase_ == 2) {
        if (messageBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = messageBuilder_.build();
        }
      }
      if (contentCase_ == 3) {
        if (deliveryTimestampBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = deliveryTimestampBuilder_.build();
        }
      }
      result.contentCase_ = contentCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.ReceiveMessageResponse) {
        return mergeFrom((apache.rocketmq.v2.ReceiveMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.ReceiveMessageResponse other) {
      if (other == apache.rocketmq.v2.ReceiveMessageResponse.getDefaultInstance()) return this;
      switch (other.getContentCase()) {
        case STATUS: {
          mergeStatus(other.getStatus());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case DELIVERY_TIMESTAMP: {
          mergeDeliveryTimestamp(other.getDeliveryTimestamp());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.ReceiveMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.ReceiveMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int contentCase_ = 0;
    private java.lang.Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return contentCase_ == 1;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public apache.rocketmq.v2.Status getStatus() {
      if (statusBuilder_ == null) {
        if (contentCase_ == 1) {
          return (apache.rocketmq.v2.Status) content_;
        }
        return apache.rocketmq.v2.Status.getDefaultInstance();
      } else {
        if (contentCase_ == 1) {
          return statusBuilder_.getMessage();
        }
        return apache.rocketmq.v2.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(
        apache.rocketmq.v2.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder mergeStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (contentCase_ == 1 &&
            content_ != apache.rocketmq.v2.Status.getDefaultInstance()) {
          content_ = apache.rocketmq.v2.Status.newBuilder((apache.rocketmq.v2.Status) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 1) {
          statusBuilder_.mergeFrom(value);
        } else {
          statusBuilder_.setMessage(value);
        }
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        if (contentCase_ == 1) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 1) {
          contentCase_ = 0;
          content_ = null;
        }
        statusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public apache.rocketmq.v2.Status.Builder getStatusBuilder() {
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
      if ((contentCase_ == 1) && (statusBuilder_ != null)) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 1) {
          return (apache.rocketmq.v2.Status) content_;
        }
        return apache.rocketmq.v2.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        if (!(contentCase_ == 1)) {
          content_ = apache.rocketmq.v2.Status.getDefaultInstance();
        }
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder>(
                (apache.rocketmq.v2.Status) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 1;
      onChanged();;
      return statusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return contentCase_ == 2;
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public apache.rocketmq.v2.Message getMessage() {
      if (messageBuilder_ == null) {
        if (contentCase_ == 2) {
          return (apache.rocketmq.v2.Message) content_;
        }
        return apache.rocketmq.v2.Message.getDefaultInstance();
      } else {
        if (contentCase_ == 2) {
          return messageBuilder_.getMessage();
        }
        return apache.rocketmq.v2.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    public Builder setMessage(apache.rocketmq.v2.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    public Builder setMessage(
        apache.rocketmq.v2.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    public Builder mergeMessage(apache.rocketmq.v2.Message value) {
      if (messageBuilder_ == null) {
        if (contentCase_ == 2 &&
            content_ != apache.rocketmq.v2.Message.getDefaultInstance()) {
          content_ = apache.rocketmq.v2.Message.newBuilder((apache.rocketmq.v2.Message) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 2) {
          messageBuilder_.mergeFrom(value);
        } else {
          messageBuilder_.setMessage(value);
        }
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    public apache.rocketmq.v2.Message.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.MessageOrBuilder getMessageOrBuilder() {
      if ((contentCase_ == 2) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 2) {
          return (apache.rocketmq.v2.Message) content_;
        }
        return apache.rocketmq.v2.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Message message = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(contentCase_ == 2)) {
          content_ = apache.rocketmq.v2.Message.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder>(
                (apache.rocketmq.v2.Message) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 2;
      onChanged();;
      return messageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deliveryTimestampBuilder_;
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     * @return Whether the deliveryTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasDeliveryTimestamp() {
      return contentCase_ == 3;
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     * @return The deliveryTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDeliveryTimestamp() {
      if (deliveryTimestampBuilder_ == null) {
        if (contentCase_ == 3) {
          return (com.google.protobuf.Timestamp) content_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (contentCase_ == 3) {
          return deliveryTimestampBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder setDeliveryTimestamp(com.google.protobuf.Timestamp value) {
      if (deliveryTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        deliveryTimestampBuilder_.setMessage(value);
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder setDeliveryTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deliveryTimestampBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        deliveryTimestampBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder mergeDeliveryTimestamp(com.google.protobuf.Timestamp value) {
      if (deliveryTimestampBuilder_ == null) {
        if (contentCase_ == 3 &&
            content_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          content_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 3) {
          deliveryTimestampBuilder_.mergeFrom(value);
        } else {
          deliveryTimestampBuilder_.setMessage(value);
        }
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder clearDeliveryTimestamp() {
      if (deliveryTimestampBuilder_ == null) {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
        }
        deliveryTimestampBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeliveryTimestampBuilder() {
      return getDeliveryTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDeliveryTimestampOrBuilder() {
      if ((contentCase_ == 3) && (deliveryTimestampBuilder_ != null)) {
        return deliveryTimestampBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 3) {
          return (com.google.protobuf.Timestamp) content_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The timestamp that brokers start to deliver status line or message.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDeliveryTimestampFieldBuilder() {
      if (deliveryTimestampBuilder_ == null) {
        if (!(contentCase_ == 3)) {
          content_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        deliveryTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 3;
      onChanged();;
      return deliveryTimestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.ReceiveMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.ReceiveMessageResponse)
  private static final apache.rocketmq.v2.ReceiveMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.ReceiveMessageResponse();
  }

  public static apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReceiveMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReceiveMessageResponse>() {
    @java.lang.Override
    public ReceiveMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReceiveMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReceiveMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReceiveMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

