// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.TelemetryCommand}
 */
public final class TelemetryCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.TelemetryCommand)
    TelemetryCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TelemetryCommand.newBuilder() to construct.
  private TelemetryCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TelemetryCommand() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TelemetryCommand();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TelemetryCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.Status.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(apache.rocketmq.v2.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            apache.rocketmq.v2.Settings.Builder subBuilder = null;
            if (commandCase_ == 2) {
              subBuilder = ((apache.rocketmq.v2.Settings) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.Settings.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.Settings) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 2;
            break;
          }
          case 26: {
            apache.rocketmq.v2.ThreadStackTrace.Builder subBuilder = null;
            if (commandCase_ == 3) {
              subBuilder = ((apache.rocketmq.v2.ThreadStackTrace) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.ThreadStackTrace.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.ThreadStackTrace) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 3;
            break;
          }
          case 34: {
            apache.rocketmq.v2.VerifyMessageResult.Builder subBuilder = null;
            if (commandCase_ == 4) {
              subBuilder = ((apache.rocketmq.v2.VerifyMessageResult) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.VerifyMessageResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.VerifyMessageResult) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 4;
            break;
          }
          case 42: {
            apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder subBuilder = null;
            if (commandCase_ == 5) {
              subBuilder = ((apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.RecoverOrphanedTransactionCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 5;
            break;
          }
          case 50: {
            apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder subBuilder = null;
            if (commandCase_ == 6) {
              subBuilder = ((apache.rocketmq.v2.PrintThreadStackTraceCommand) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.PrintThreadStackTraceCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.PrintThreadStackTraceCommand) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 6;
            break;
          }
          case 58: {
            apache.rocketmq.v2.VerifyMessageCommand.Builder subBuilder = null;
            if (commandCase_ == 7) {
              subBuilder = ((apache.rocketmq.v2.VerifyMessageCommand) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.VerifyMessageCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.VerifyMessageCommand) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 7;
            break;
          }
          case 66: {
            apache.rocketmq.v2.ReconnectEndpointsCommand.Builder subBuilder = null;
            if (commandCase_ == 8) {
              subBuilder = ((apache.rocketmq.v2.ReconnectEndpointsCommand) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.ReconnectEndpointsCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.ReconnectEndpointsCommand) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 8;
            break;
          }
          case 74: {
            apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder subBuilder = null;
            if (commandCase_ == 9) {
              subBuilder = ((apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_).toBuilder();
            }
            command_ =
                input.readMessage(apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 9;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.TelemetryCommand.class, apache.rocketmq.v2.TelemetryCommand.Builder.class);
  }

  private int bitField0_;
  private int commandCase_ = 0;
  private java.lang.Object command_;
  public enum CommandCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SETTINGS(2),
    THREAD_STACK_TRACE(3),
    VERIFY_MESSAGE_RESULT(4),
    RECOVER_ORPHANED_TRANSACTION_COMMAND(5),
    PRINT_THREAD_STACK_TRACE_COMMAND(6),
    VERIFY_MESSAGE_COMMAND(7),
    RECONNECT_ENDPOINTS_COMMAND(8),
    NOTIFY_UNSUBSCRIBE_LITE_COMMAND(9),
    COMMAND_NOT_SET(0);
    private final int value;
    private CommandCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandCase valueOf(int value) {
      return forNumber(value);
    }

    public static CommandCase forNumber(int value) {
      switch (value) {
        case 2: return SETTINGS;
        case 3: return THREAD_STACK_TRACE;
        case 4: return VERIFY_MESSAGE_RESULT;
        case 5: return RECOVER_ORPHANED_TRANSACTION_COMMAND;
        case 6: return PRINT_THREAD_STACK_TRACE_COMMAND;
        case 7: return VERIFY_MESSAGE_COMMAND;
        case 8: return RECONNECT_ENDPOINTS_COMMAND;
        case 9: return NOTIFY_UNSUBSCRIBE_LITE_COMMAND;
        case 0: return COMMAND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CommandCase
  getCommandCase() {
    return CommandCase.forNumber(
        commandCase_);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private apache.rocketmq.v2.Status status_;
  /**
   * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Status getStatus() {
    return status_ == null ? apache.rocketmq.v2.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? apache.rocketmq.v2.Status.getDefaultInstance() : status_;
  }

  public static final int SETTINGS_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Client settings
   * </pre>
   *
   * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
   * @return Whether the settings field is set.
   */
  @java.lang.Override
  public boolean hasSettings() {
    return commandCase_ == 2;
  }
  /**
   * <pre>
   * Client settings
   * </pre>
   *
   * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
   * @return The settings.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Settings getSettings() {
    if (commandCase_ == 2) {
       return (apache.rocketmq.v2.Settings) command_;
    }
    return apache.rocketmq.v2.Settings.getDefaultInstance();
  }
  /**
   * <pre>
   * Client settings
   * </pre>
   *
   * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.SettingsOrBuilder getSettingsOrBuilder() {
    if (commandCase_ == 2) {
       return (apache.rocketmq.v2.Settings) command_;
    }
    return apache.rocketmq.v2.Settings.getDefaultInstance();
  }

  public static final int THREAD_STACK_TRACE_FIELD_NUMBER = 3;
  /**
   * <pre>
   * These messages are from client.
   * Report thread stack trace to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
   * @return Whether the threadStackTrace field is set.
   */
  @java.lang.Override
  public boolean hasThreadStackTrace() {
    return commandCase_ == 3;
  }
  /**
   * <pre>
   * These messages are from client.
   * Report thread stack trace to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
   * @return The threadStackTrace.
   */
  @java.lang.Override
  public apache.rocketmq.v2.ThreadStackTrace getThreadStackTrace() {
    if (commandCase_ == 3) {
       return (apache.rocketmq.v2.ThreadStackTrace) command_;
    }
    return apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
  }
  /**
   * <pre>
   * These messages are from client.
   * Report thread stack trace to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ThreadStackTraceOrBuilder getThreadStackTraceOrBuilder() {
    if (commandCase_ == 3) {
       return (apache.rocketmq.v2.ThreadStackTrace) command_;
    }
    return apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
  }

  public static final int VERIFY_MESSAGE_RESULT_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Report message verify result to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
   * @return Whether the verifyMessageResult field is set.
   */
  @java.lang.Override
  public boolean hasVerifyMessageResult() {
    return commandCase_ == 4;
  }
  /**
   * <pre>
   * Report message verify result to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
   * @return The verifyMessageResult.
   */
  @java.lang.Override
  public apache.rocketmq.v2.VerifyMessageResult getVerifyMessageResult() {
    if (commandCase_ == 4) {
       return (apache.rocketmq.v2.VerifyMessageResult) command_;
    }
    return apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
  }
  /**
   * <pre>
   * Report message verify result to server.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.VerifyMessageResultOrBuilder getVerifyMessageResultOrBuilder() {
    if (commandCase_ == 4) {
       return (apache.rocketmq.v2.VerifyMessageResult) command_;
    }
    return apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
  }

  public static final int RECOVER_ORPHANED_TRANSACTION_COMMAND_FIELD_NUMBER = 5;
  /**
   * <pre>
   * There messages are from server.
   * Request client to recover the orphaned transaction message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
   * @return Whether the recoverOrphanedTransactionCommand field is set.
   */
  @java.lang.Override
  public boolean hasRecoverOrphanedTransactionCommand() {
    return commandCase_ == 5;
  }
  /**
   * <pre>
   * There messages are from server.
   * Request client to recover the orphaned transaction message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
   * @return The recoverOrphanedTransactionCommand.
   */
  @java.lang.Override
  public apache.rocketmq.v2.RecoverOrphanedTransactionCommand getRecoverOrphanedTransactionCommand() {
    if (commandCase_ == 5) {
       return (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_;
    }
    return apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * There messages are from server.
   * Request client to recover the orphaned transaction message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.RecoverOrphanedTransactionCommandOrBuilder getRecoverOrphanedTransactionCommandOrBuilder() {
    if (commandCase_ == 5) {
       return (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_;
    }
    return apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
  }

  public static final int PRINT_THREAD_STACK_TRACE_COMMAND_FIELD_NUMBER = 6;
  /**
   * <pre>
   * Request client to print thread stack trace.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
   * @return Whether the printThreadStackTraceCommand field is set.
   */
  @java.lang.Override
  public boolean hasPrintThreadStackTraceCommand() {
    return commandCase_ == 6;
  }
  /**
   * <pre>
   * Request client to print thread stack trace.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
   * @return The printThreadStackTraceCommand.
   */
  @java.lang.Override
  public apache.rocketmq.v2.PrintThreadStackTraceCommand getPrintThreadStackTraceCommand() {
    if (commandCase_ == 6) {
       return (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_;
    }
    return apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * Request client to print thread stack trace.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.PrintThreadStackTraceCommandOrBuilder getPrintThreadStackTraceCommandOrBuilder() {
    if (commandCase_ == 6) {
       return (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_;
    }
    return apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
  }

  public static final int VERIFY_MESSAGE_COMMAND_FIELD_NUMBER = 7;
  /**
   * <pre>
   * Request client to verify the consumption of the appointed message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
   * @return Whether the verifyMessageCommand field is set.
   */
  @java.lang.Override
  public boolean hasVerifyMessageCommand() {
    return commandCase_ == 7;
  }
  /**
   * <pre>
   * Request client to verify the consumption of the appointed message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
   * @return The verifyMessageCommand.
   */
  @java.lang.Override
  public apache.rocketmq.v2.VerifyMessageCommand getVerifyMessageCommand() {
    if (commandCase_ == 7) {
       return (apache.rocketmq.v2.VerifyMessageCommand) command_;
    }
    return apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * Request client to verify the consumption of the appointed message.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.VerifyMessageCommandOrBuilder getVerifyMessageCommandOrBuilder() {
    if (commandCase_ == 7) {
       return (apache.rocketmq.v2.VerifyMessageCommand) command_;
    }
    return apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
  }

  public static final int RECONNECT_ENDPOINTS_COMMAND_FIELD_NUMBER = 8;
  /**
   * <pre>
   * Request client to reconnect server use the latest endpoints.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
   * @return Whether the reconnectEndpointsCommand field is set.
   */
  @java.lang.Override
  public boolean hasReconnectEndpointsCommand() {
    return commandCase_ == 8;
  }
  /**
   * <pre>
   * Request client to reconnect server use the latest endpoints.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
   * @return The reconnectEndpointsCommand.
   */
  @java.lang.Override
  public apache.rocketmq.v2.ReconnectEndpointsCommand getReconnectEndpointsCommand() {
    if (commandCase_ == 8) {
       return (apache.rocketmq.v2.ReconnectEndpointsCommand) command_;
    }
    return apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * Request client to reconnect server use the latest endpoints.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ReconnectEndpointsCommandOrBuilder getReconnectEndpointsCommandOrBuilder() {
    if (commandCase_ == 8) {
       return (apache.rocketmq.v2.ReconnectEndpointsCommand) command_;
    }
    return apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
  }

  public static final int NOTIFY_UNSUBSCRIBE_LITE_COMMAND_FIELD_NUMBER = 9;
  /**
   * <pre>
   * Request client to unsubscribe lite topic.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
   * @return Whether the notifyUnsubscribeLiteCommand field is set.
   */
  @java.lang.Override
  public boolean hasNotifyUnsubscribeLiteCommand() {
    return commandCase_ == 9;
  }
  /**
   * <pre>
   * Request client to unsubscribe lite topic.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
   * @return The notifyUnsubscribeLiteCommand.
   */
  @java.lang.Override
  public apache.rocketmq.v2.NotifyUnsubscribeLiteCommand getNotifyUnsubscribeLiteCommand() {
    if (commandCase_ == 9) {
       return (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_;
    }
    return apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * Request client to unsubscribe lite topic.
   * </pre>
   *
   * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.NotifyUnsubscribeLiteCommandOrBuilder getNotifyUnsubscribeLiteCommandOrBuilder() {
    if (commandCase_ == 9) {
       return (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_;
    }
    return apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStatus());
    }
    if (commandCase_ == 2) {
      output.writeMessage(2, (apache.rocketmq.v2.Settings) command_);
    }
    if (commandCase_ == 3) {
      output.writeMessage(3, (apache.rocketmq.v2.ThreadStackTrace) command_);
    }
    if (commandCase_ == 4) {
      output.writeMessage(4, (apache.rocketmq.v2.VerifyMessageResult) command_);
    }
    if (commandCase_ == 5) {
      output.writeMessage(5, (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_);
    }
    if (commandCase_ == 6) {
      output.writeMessage(6, (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_);
    }
    if (commandCase_ == 7) {
      output.writeMessage(7, (apache.rocketmq.v2.VerifyMessageCommand) command_);
    }
    if (commandCase_ == 8) {
      output.writeMessage(8, (apache.rocketmq.v2.ReconnectEndpointsCommand) command_);
    }
    if (commandCase_ == 9) {
      output.writeMessage(9, (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (commandCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (apache.rocketmq.v2.Settings) command_);
    }
    if (commandCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (apache.rocketmq.v2.ThreadStackTrace) command_);
    }
    if (commandCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (apache.rocketmq.v2.VerifyMessageResult) command_);
    }
    if (commandCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_);
    }
    if (commandCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_);
    }
    if (commandCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (apache.rocketmq.v2.VerifyMessageCommand) command_);
    }
    if (commandCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (apache.rocketmq.v2.ReconnectEndpointsCommand) command_);
    }
    if (commandCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.TelemetryCommand)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.TelemetryCommand other = (apache.rocketmq.v2.TelemetryCommand) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getCommandCase().equals(other.getCommandCase())) return false;
    switch (commandCase_) {
      case 2:
        if (!getSettings()
            .equals(other.getSettings())) return false;
        break;
      case 3:
        if (!getThreadStackTrace()
            .equals(other.getThreadStackTrace())) return false;
        break;
      case 4:
        if (!getVerifyMessageResult()
            .equals(other.getVerifyMessageResult())) return false;
        break;
      case 5:
        if (!getRecoverOrphanedTransactionCommand()
            .equals(other.getRecoverOrphanedTransactionCommand())) return false;
        break;
      case 6:
        if (!getPrintThreadStackTraceCommand()
            .equals(other.getPrintThreadStackTraceCommand())) return false;
        break;
      case 7:
        if (!getVerifyMessageCommand()
            .equals(other.getVerifyMessageCommand())) return false;
        break;
      case 8:
        if (!getReconnectEndpointsCommand()
            .equals(other.getReconnectEndpointsCommand())) return false;
        break;
      case 9:
        if (!getNotifyUnsubscribeLiteCommand()
            .equals(other.getNotifyUnsubscribeLiteCommand())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    switch (commandCase_) {
      case 2:
        hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getSettings().hashCode();
        break;
      case 3:
        hash = (37 * hash) + THREAD_STACK_TRACE_FIELD_NUMBER;
        hash = (53 * hash) + getThreadStackTrace().hashCode();
        break;
      case 4:
        hash = (37 * hash) + VERIFY_MESSAGE_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getVerifyMessageResult().hashCode();
        break;
      case 5:
        hash = (37 * hash) + RECOVER_ORPHANED_TRANSACTION_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getRecoverOrphanedTransactionCommand().hashCode();
        break;
      case 6:
        hash = (37 * hash) + PRINT_THREAD_STACK_TRACE_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getPrintThreadStackTraceCommand().hashCode();
        break;
      case 7:
        hash = (37 * hash) + VERIFY_MESSAGE_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getVerifyMessageCommand().hashCode();
        break;
      case 8:
        hash = (37 * hash) + RECONNECT_ENDPOINTS_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getReconnectEndpointsCommand().hashCode();
        break;
      case 9:
        hash = (37 * hash) + NOTIFY_UNSUBSCRIBE_LITE_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyUnsubscribeLiteCommand().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.TelemetryCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.TelemetryCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.TelemetryCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.TelemetryCommand)
      apache.rocketmq.v2.TelemetryCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.TelemetryCommand.class, apache.rocketmq.v2.TelemetryCommand.Builder.class);
    }

    // Construct using apache.rocketmq.v2.TelemetryCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      commandCase_ = 0;
      command_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.TelemetryCommand getDefaultInstanceForType() {
      return apache.rocketmq.v2.TelemetryCommand.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.TelemetryCommand build() {
      apache.rocketmq.v2.TelemetryCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.TelemetryCommand buildPartial() {
      apache.rocketmq.v2.TelemetryCommand result = new apache.rocketmq.v2.TelemetryCommand(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (commandCase_ == 2) {
        if (settingsBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = settingsBuilder_.build();
        }
      }
      if (commandCase_ == 3) {
        if (threadStackTraceBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = threadStackTraceBuilder_.build();
        }
      }
      if (commandCase_ == 4) {
        if (verifyMessageResultBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = verifyMessageResultBuilder_.build();
        }
      }
      if (commandCase_ == 5) {
        if (recoverOrphanedTransactionCommandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = recoverOrphanedTransactionCommandBuilder_.build();
        }
      }
      if (commandCase_ == 6) {
        if (printThreadStackTraceCommandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = printThreadStackTraceCommandBuilder_.build();
        }
      }
      if (commandCase_ == 7) {
        if (verifyMessageCommandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = verifyMessageCommandBuilder_.build();
        }
      }
      if (commandCase_ == 8) {
        if (reconnectEndpointsCommandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = reconnectEndpointsCommandBuilder_.build();
        }
      }
      if (commandCase_ == 9) {
        if (notifyUnsubscribeLiteCommandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = notifyUnsubscribeLiteCommandBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.commandCase_ = commandCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.TelemetryCommand) {
        return mergeFrom((apache.rocketmq.v2.TelemetryCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.TelemetryCommand other) {
      if (other == apache.rocketmq.v2.TelemetryCommand.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      switch (other.getCommandCase()) {
        case SETTINGS: {
          mergeSettings(other.getSettings());
          break;
        }
        case THREAD_STACK_TRACE: {
          mergeThreadStackTrace(other.getThreadStackTrace());
          break;
        }
        case VERIFY_MESSAGE_RESULT: {
          mergeVerifyMessageResult(other.getVerifyMessageResult());
          break;
        }
        case RECOVER_ORPHANED_TRANSACTION_COMMAND: {
          mergeRecoverOrphanedTransactionCommand(other.getRecoverOrphanedTransactionCommand());
          break;
        }
        case PRINT_THREAD_STACK_TRACE_COMMAND: {
          mergePrintThreadStackTraceCommand(other.getPrintThreadStackTraceCommand());
          break;
        }
        case VERIFY_MESSAGE_COMMAND: {
          mergeVerifyMessageCommand(other.getVerifyMessageCommand());
          break;
        }
        case RECONNECT_ENDPOINTS_COMMAND: {
          mergeReconnectEndpointsCommand(other.getReconnectEndpointsCommand());
          break;
        }
        case NOTIFY_UNSUBSCRIBE_LITE_COMMAND: {
          mergeNotifyUnsubscribeLiteCommand(other.getNotifyUnsubscribeLiteCommand());
          break;
        }
        case COMMAND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.TelemetryCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.TelemetryCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int commandCase_ = 0;
    private java.lang.Object command_;
    public CommandCase
        getCommandCase() {
      return CommandCase.forNumber(
          commandCase_);
    }

    public Builder clearCommand() {
      commandCase_ = 0;
      command_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private apache.rocketmq.v2.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> statusBuilder_;
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     * @return The status.
     */
    public apache.rocketmq.v2.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? apache.rocketmq.v2.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(
        apache.rocketmq.v2.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder mergeStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            status_ != null &&
            status_ != apache.rocketmq.v2.Status.getDefaultInstance()) {
          status_ =
            apache.rocketmq.v2.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public apache.rocketmq.v2.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            apache.rocketmq.v2.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>optional .apache.rocketmq.v2.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Settings, apache.rocketmq.v2.Settings.Builder, apache.rocketmq.v2.SettingsOrBuilder> settingsBuilder_;
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     * @return Whether the settings field is set.
     */
    @java.lang.Override
    public boolean hasSettings() {
      return commandCase_ == 2;
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     * @return The settings.
     */
    @java.lang.Override
    public apache.rocketmq.v2.Settings getSettings() {
      if (settingsBuilder_ == null) {
        if (commandCase_ == 2) {
          return (apache.rocketmq.v2.Settings) command_;
        }
        return apache.rocketmq.v2.Settings.getDefaultInstance();
      } else {
        if (commandCase_ == 2) {
          return settingsBuilder_.getMessage();
        }
        return apache.rocketmq.v2.Settings.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    public Builder setSettings(apache.rocketmq.v2.Settings value) {
      if (settingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        settingsBuilder_.setMessage(value);
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    public Builder setSettings(
        apache.rocketmq.v2.Settings.Builder builderForValue) {
      if (settingsBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        settingsBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    public Builder mergeSettings(apache.rocketmq.v2.Settings value) {
      if (settingsBuilder_ == null) {
        if (commandCase_ == 2 &&
            command_ != apache.rocketmq.v2.Settings.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.Settings.newBuilder((apache.rocketmq.v2.Settings) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 2) {
          settingsBuilder_.mergeFrom(value);
        } else {
          settingsBuilder_.setMessage(value);
        }
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    public Builder clearSettings() {
      if (settingsBuilder_ == null) {
        if (commandCase_ == 2) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 2) {
          commandCase_ = 0;
          command_ = null;
        }
        settingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    public apache.rocketmq.v2.Settings.Builder getSettingsBuilder() {
      return getSettingsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.SettingsOrBuilder getSettingsOrBuilder() {
      if ((commandCase_ == 2) && (settingsBuilder_ != null)) {
        return settingsBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 2) {
          return (apache.rocketmq.v2.Settings) command_;
        }
        return apache.rocketmq.v2.Settings.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Client settings
     * </pre>
     *
     * <code>.apache.rocketmq.v2.Settings settings = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Settings, apache.rocketmq.v2.Settings.Builder, apache.rocketmq.v2.SettingsOrBuilder> 
        getSettingsFieldBuilder() {
      if (settingsBuilder_ == null) {
        if (!(commandCase_ == 2)) {
          command_ = apache.rocketmq.v2.Settings.getDefaultInstance();
        }
        settingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Settings, apache.rocketmq.v2.Settings.Builder, apache.rocketmq.v2.SettingsOrBuilder>(
                (apache.rocketmq.v2.Settings) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 2;
      onChanged();;
      return settingsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ThreadStackTrace, apache.rocketmq.v2.ThreadStackTrace.Builder, apache.rocketmq.v2.ThreadStackTraceOrBuilder> threadStackTraceBuilder_;
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     * @return Whether the threadStackTrace field is set.
     */
    @java.lang.Override
    public boolean hasThreadStackTrace() {
      return commandCase_ == 3;
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     * @return The threadStackTrace.
     */
    @java.lang.Override
    public apache.rocketmq.v2.ThreadStackTrace getThreadStackTrace() {
      if (threadStackTraceBuilder_ == null) {
        if (commandCase_ == 3) {
          return (apache.rocketmq.v2.ThreadStackTrace) command_;
        }
        return apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
      } else {
        if (commandCase_ == 3) {
          return threadStackTraceBuilder_.getMessage();
        }
        return apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    public Builder setThreadStackTrace(apache.rocketmq.v2.ThreadStackTrace value) {
      if (threadStackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        threadStackTraceBuilder_.setMessage(value);
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    public Builder setThreadStackTrace(
        apache.rocketmq.v2.ThreadStackTrace.Builder builderForValue) {
      if (threadStackTraceBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        threadStackTraceBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    public Builder mergeThreadStackTrace(apache.rocketmq.v2.ThreadStackTrace value) {
      if (threadStackTraceBuilder_ == null) {
        if (commandCase_ == 3 &&
            command_ != apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.ThreadStackTrace.newBuilder((apache.rocketmq.v2.ThreadStackTrace) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 3) {
          threadStackTraceBuilder_.mergeFrom(value);
        } else {
          threadStackTraceBuilder_.setMessage(value);
        }
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    public Builder clearThreadStackTrace() {
      if (threadStackTraceBuilder_ == null) {
        if (commandCase_ == 3) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 3) {
          commandCase_ = 0;
          command_ = null;
        }
        threadStackTraceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    public apache.rocketmq.v2.ThreadStackTrace.Builder getThreadStackTraceBuilder() {
      return getThreadStackTraceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.ThreadStackTraceOrBuilder getThreadStackTraceOrBuilder() {
      if ((commandCase_ == 3) && (threadStackTraceBuilder_ != null)) {
        return threadStackTraceBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 3) {
          return (apache.rocketmq.v2.ThreadStackTrace) command_;
        }
        return apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * These messages are from client.
     * Report thread stack trace to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ThreadStackTrace thread_stack_trace = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ThreadStackTrace, apache.rocketmq.v2.ThreadStackTrace.Builder, apache.rocketmq.v2.ThreadStackTraceOrBuilder> 
        getThreadStackTraceFieldBuilder() {
      if (threadStackTraceBuilder_ == null) {
        if (!(commandCase_ == 3)) {
          command_ = apache.rocketmq.v2.ThreadStackTrace.getDefaultInstance();
        }
        threadStackTraceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.ThreadStackTrace, apache.rocketmq.v2.ThreadStackTrace.Builder, apache.rocketmq.v2.ThreadStackTraceOrBuilder>(
                (apache.rocketmq.v2.ThreadStackTrace) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 3;
      onChanged();;
      return threadStackTraceBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.VerifyMessageResult, apache.rocketmq.v2.VerifyMessageResult.Builder, apache.rocketmq.v2.VerifyMessageResultOrBuilder> verifyMessageResultBuilder_;
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     * @return Whether the verifyMessageResult field is set.
     */
    @java.lang.Override
    public boolean hasVerifyMessageResult() {
      return commandCase_ == 4;
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     * @return The verifyMessageResult.
     */
    @java.lang.Override
    public apache.rocketmq.v2.VerifyMessageResult getVerifyMessageResult() {
      if (verifyMessageResultBuilder_ == null) {
        if (commandCase_ == 4) {
          return (apache.rocketmq.v2.VerifyMessageResult) command_;
        }
        return apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
      } else {
        if (commandCase_ == 4) {
          return verifyMessageResultBuilder_.getMessage();
        }
        return apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    public Builder setVerifyMessageResult(apache.rocketmq.v2.VerifyMessageResult value) {
      if (verifyMessageResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        verifyMessageResultBuilder_.setMessage(value);
      }
      commandCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    public Builder setVerifyMessageResult(
        apache.rocketmq.v2.VerifyMessageResult.Builder builderForValue) {
      if (verifyMessageResultBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        verifyMessageResultBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    public Builder mergeVerifyMessageResult(apache.rocketmq.v2.VerifyMessageResult value) {
      if (verifyMessageResultBuilder_ == null) {
        if (commandCase_ == 4 &&
            command_ != apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.VerifyMessageResult.newBuilder((apache.rocketmq.v2.VerifyMessageResult) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 4) {
          verifyMessageResultBuilder_.mergeFrom(value);
        } else {
          verifyMessageResultBuilder_.setMessage(value);
        }
      }
      commandCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    public Builder clearVerifyMessageResult() {
      if (verifyMessageResultBuilder_ == null) {
        if (commandCase_ == 4) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 4) {
          commandCase_ = 0;
          command_ = null;
        }
        verifyMessageResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    public apache.rocketmq.v2.VerifyMessageResult.Builder getVerifyMessageResultBuilder() {
      return getVerifyMessageResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.VerifyMessageResultOrBuilder getVerifyMessageResultOrBuilder() {
      if ((commandCase_ == 4) && (verifyMessageResultBuilder_ != null)) {
        return verifyMessageResultBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 4) {
          return (apache.rocketmq.v2.VerifyMessageResult) command_;
        }
        return apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Report message verify result to server.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageResult verify_message_result = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.VerifyMessageResult, apache.rocketmq.v2.VerifyMessageResult.Builder, apache.rocketmq.v2.VerifyMessageResultOrBuilder> 
        getVerifyMessageResultFieldBuilder() {
      if (verifyMessageResultBuilder_ == null) {
        if (!(commandCase_ == 4)) {
          command_ = apache.rocketmq.v2.VerifyMessageResult.getDefaultInstance();
        }
        verifyMessageResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.VerifyMessageResult, apache.rocketmq.v2.VerifyMessageResult.Builder, apache.rocketmq.v2.VerifyMessageResultOrBuilder>(
                (apache.rocketmq.v2.VerifyMessageResult) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 4;
      onChanged();;
      return verifyMessageResultBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.RecoverOrphanedTransactionCommand, apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder, apache.rocketmq.v2.RecoverOrphanedTransactionCommandOrBuilder> recoverOrphanedTransactionCommandBuilder_;
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     * @return Whether the recoverOrphanedTransactionCommand field is set.
     */
    @java.lang.Override
    public boolean hasRecoverOrphanedTransactionCommand() {
      return commandCase_ == 5;
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     * @return The recoverOrphanedTransactionCommand.
     */
    @java.lang.Override
    public apache.rocketmq.v2.RecoverOrphanedTransactionCommand getRecoverOrphanedTransactionCommand() {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        if (commandCase_ == 5) {
          return (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_;
        }
        return apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
      } else {
        if (commandCase_ == 5) {
          return recoverOrphanedTransactionCommandBuilder_.getMessage();
        }
        return apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    public Builder setRecoverOrphanedTransactionCommand(apache.rocketmq.v2.RecoverOrphanedTransactionCommand value) {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        recoverOrphanedTransactionCommandBuilder_.setMessage(value);
      }
      commandCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    public Builder setRecoverOrphanedTransactionCommand(
        apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder builderForValue) {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        recoverOrphanedTransactionCommandBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    public Builder mergeRecoverOrphanedTransactionCommand(apache.rocketmq.v2.RecoverOrphanedTransactionCommand value) {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        if (commandCase_ == 5 &&
            command_ != apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.RecoverOrphanedTransactionCommand.newBuilder((apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 5) {
          recoverOrphanedTransactionCommandBuilder_.mergeFrom(value);
        } else {
          recoverOrphanedTransactionCommandBuilder_.setMessage(value);
        }
      }
      commandCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    public Builder clearRecoverOrphanedTransactionCommand() {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        if (commandCase_ == 5) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 5) {
          commandCase_ = 0;
          command_ = null;
        }
        recoverOrphanedTransactionCommandBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    public apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder getRecoverOrphanedTransactionCommandBuilder() {
      return getRecoverOrphanedTransactionCommandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.RecoverOrphanedTransactionCommandOrBuilder getRecoverOrphanedTransactionCommandOrBuilder() {
      if ((commandCase_ == 5) && (recoverOrphanedTransactionCommandBuilder_ != null)) {
        return recoverOrphanedTransactionCommandBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 5) {
          return (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_;
        }
        return apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * There messages are from server.
     * Request client to recover the orphaned transaction message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.RecoverOrphanedTransactionCommand recover_orphaned_transaction_command = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.RecoverOrphanedTransactionCommand, apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder, apache.rocketmq.v2.RecoverOrphanedTransactionCommandOrBuilder> 
        getRecoverOrphanedTransactionCommandFieldBuilder() {
      if (recoverOrphanedTransactionCommandBuilder_ == null) {
        if (!(commandCase_ == 5)) {
          command_ = apache.rocketmq.v2.RecoverOrphanedTransactionCommand.getDefaultInstance();
        }
        recoverOrphanedTransactionCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.RecoverOrphanedTransactionCommand, apache.rocketmq.v2.RecoverOrphanedTransactionCommand.Builder, apache.rocketmq.v2.RecoverOrphanedTransactionCommandOrBuilder>(
                (apache.rocketmq.v2.RecoverOrphanedTransactionCommand) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 5;
      onChanged();;
      return recoverOrphanedTransactionCommandBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.PrintThreadStackTraceCommand, apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder, apache.rocketmq.v2.PrintThreadStackTraceCommandOrBuilder> printThreadStackTraceCommandBuilder_;
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     * @return Whether the printThreadStackTraceCommand field is set.
     */
    @java.lang.Override
    public boolean hasPrintThreadStackTraceCommand() {
      return commandCase_ == 6;
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     * @return The printThreadStackTraceCommand.
     */
    @java.lang.Override
    public apache.rocketmq.v2.PrintThreadStackTraceCommand getPrintThreadStackTraceCommand() {
      if (printThreadStackTraceCommandBuilder_ == null) {
        if (commandCase_ == 6) {
          return (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_;
        }
        return apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
      } else {
        if (commandCase_ == 6) {
          return printThreadStackTraceCommandBuilder_.getMessage();
        }
        return apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    public Builder setPrintThreadStackTraceCommand(apache.rocketmq.v2.PrintThreadStackTraceCommand value) {
      if (printThreadStackTraceCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        printThreadStackTraceCommandBuilder_.setMessage(value);
      }
      commandCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    public Builder setPrintThreadStackTraceCommand(
        apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder builderForValue) {
      if (printThreadStackTraceCommandBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        printThreadStackTraceCommandBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    public Builder mergePrintThreadStackTraceCommand(apache.rocketmq.v2.PrintThreadStackTraceCommand value) {
      if (printThreadStackTraceCommandBuilder_ == null) {
        if (commandCase_ == 6 &&
            command_ != apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.PrintThreadStackTraceCommand.newBuilder((apache.rocketmq.v2.PrintThreadStackTraceCommand) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 6) {
          printThreadStackTraceCommandBuilder_.mergeFrom(value);
        } else {
          printThreadStackTraceCommandBuilder_.setMessage(value);
        }
      }
      commandCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    public Builder clearPrintThreadStackTraceCommand() {
      if (printThreadStackTraceCommandBuilder_ == null) {
        if (commandCase_ == 6) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 6) {
          commandCase_ = 0;
          command_ = null;
        }
        printThreadStackTraceCommandBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    public apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder getPrintThreadStackTraceCommandBuilder() {
      return getPrintThreadStackTraceCommandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.PrintThreadStackTraceCommandOrBuilder getPrintThreadStackTraceCommandOrBuilder() {
      if ((commandCase_ == 6) && (printThreadStackTraceCommandBuilder_ != null)) {
        return printThreadStackTraceCommandBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 6) {
          return (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_;
        }
        return apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to print thread stack trace.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.PrintThreadStackTraceCommand print_thread_stack_trace_command = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.PrintThreadStackTraceCommand, apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder, apache.rocketmq.v2.PrintThreadStackTraceCommandOrBuilder> 
        getPrintThreadStackTraceCommandFieldBuilder() {
      if (printThreadStackTraceCommandBuilder_ == null) {
        if (!(commandCase_ == 6)) {
          command_ = apache.rocketmq.v2.PrintThreadStackTraceCommand.getDefaultInstance();
        }
        printThreadStackTraceCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.PrintThreadStackTraceCommand, apache.rocketmq.v2.PrintThreadStackTraceCommand.Builder, apache.rocketmq.v2.PrintThreadStackTraceCommandOrBuilder>(
                (apache.rocketmq.v2.PrintThreadStackTraceCommand) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 6;
      onChanged();;
      return printThreadStackTraceCommandBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.VerifyMessageCommand, apache.rocketmq.v2.VerifyMessageCommand.Builder, apache.rocketmq.v2.VerifyMessageCommandOrBuilder> verifyMessageCommandBuilder_;
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     * @return Whether the verifyMessageCommand field is set.
     */
    @java.lang.Override
    public boolean hasVerifyMessageCommand() {
      return commandCase_ == 7;
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     * @return The verifyMessageCommand.
     */
    @java.lang.Override
    public apache.rocketmq.v2.VerifyMessageCommand getVerifyMessageCommand() {
      if (verifyMessageCommandBuilder_ == null) {
        if (commandCase_ == 7) {
          return (apache.rocketmq.v2.VerifyMessageCommand) command_;
        }
        return apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
      } else {
        if (commandCase_ == 7) {
          return verifyMessageCommandBuilder_.getMessage();
        }
        return apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    public Builder setVerifyMessageCommand(apache.rocketmq.v2.VerifyMessageCommand value) {
      if (verifyMessageCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        verifyMessageCommandBuilder_.setMessage(value);
      }
      commandCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    public Builder setVerifyMessageCommand(
        apache.rocketmq.v2.VerifyMessageCommand.Builder builderForValue) {
      if (verifyMessageCommandBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        verifyMessageCommandBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    public Builder mergeVerifyMessageCommand(apache.rocketmq.v2.VerifyMessageCommand value) {
      if (verifyMessageCommandBuilder_ == null) {
        if (commandCase_ == 7 &&
            command_ != apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.VerifyMessageCommand.newBuilder((apache.rocketmq.v2.VerifyMessageCommand) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 7) {
          verifyMessageCommandBuilder_.mergeFrom(value);
        } else {
          verifyMessageCommandBuilder_.setMessage(value);
        }
      }
      commandCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    public Builder clearVerifyMessageCommand() {
      if (verifyMessageCommandBuilder_ == null) {
        if (commandCase_ == 7) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 7) {
          commandCase_ = 0;
          command_ = null;
        }
        verifyMessageCommandBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    public apache.rocketmq.v2.VerifyMessageCommand.Builder getVerifyMessageCommandBuilder() {
      return getVerifyMessageCommandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.VerifyMessageCommandOrBuilder getVerifyMessageCommandOrBuilder() {
      if ((commandCase_ == 7) && (verifyMessageCommandBuilder_ != null)) {
        return verifyMessageCommandBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 7) {
          return (apache.rocketmq.v2.VerifyMessageCommand) command_;
        }
        return apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to verify the consumption of the appointed message.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.VerifyMessageCommand verify_message_command = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.VerifyMessageCommand, apache.rocketmq.v2.VerifyMessageCommand.Builder, apache.rocketmq.v2.VerifyMessageCommandOrBuilder> 
        getVerifyMessageCommandFieldBuilder() {
      if (verifyMessageCommandBuilder_ == null) {
        if (!(commandCase_ == 7)) {
          command_ = apache.rocketmq.v2.VerifyMessageCommand.getDefaultInstance();
        }
        verifyMessageCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.VerifyMessageCommand, apache.rocketmq.v2.VerifyMessageCommand.Builder, apache.rocketmq.v2.VerifyMessageCommandOrBuilder>(
                (apache.rocketmq.v2.VerifyMessageCommand) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 7;
      onChanged();;
      return verifyMessageCommandBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ReconnectEndpointsCommand, apache.rocketmq.v2.ReconnectEndpointsCommand.Builder, apache.rocketmq.v2.ReconnectEndpointsCommandOrBuilder> reconnectEndpointsCommandBuilder_;
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     * @return Whether the reconnectEndpointsCommand field is set.
     */
    @java.lang.Override
    public boolean hasReconnectEndpointsCommand() {
      return commandCase_ == 8;
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     * @return The reconnectEndpointsCommand.
     */
    @java.lang.Override
    public apache.rocketmq.v2.ReconnectEndpointsCommand getReconnectEndpointsCommand() {
      if (reconnectEndpointsCommandBuilder_ == null) {
        if (commandCase_ == 8) {
          return (apache.rocketmq.v2.ReconnectEndpointsCommand) command_;
        }
        return apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
      } else {
        if (commandCase_ == 8) {
          return reconnectEndpointsCommandBuilder_.getMessage();
        }
        return apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    public Builder setReconnectEndpointsCommand(apache.rocketmq.v2.ReconnectEndpointsCommand value) {
      if (reconnectEndpointsCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        reconnectEndpointsCommandBuilder_.setMessage(value);
      }
      commandCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    public Builder setReconnectEndpointsCommand(
        apache.rocketmq.v2.ReconnectEndpointsCommand.Builder builderForValue) {
      if (reconnectEndpointsCommandBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        reconnectEndpointsCommandBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    public Builder mergeReconnectEndpointsCommand(apache.rocketmq.v2.ReconnectEndpointsCommand value) {
      if (reconnectEndpointsCommandBuilder_ == null) {
        if (commandCase_ == 8 &&
            command_ != apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.ReconnectEndpointsCommand.newBuilder((apache.rocketmq.v2.ReconnectEndpointsCommand) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 8) {
          reconnectEndpointsCommandBuilder_.mergeFrom(value);
        } else {
          reconnectEndpointsCommandBuilder_.setMessage(value);
        }
      }
      commandCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    public Builder clearReconnectEndpointsCommand() {
      if (reconnectEndpointsCommandBuilder_ == null) {
        if (commandCase_ == 8) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 8) {
          commandCase_ = 0;
          command_ = null;
        }
        reconnectEndpointsCommandBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    public apache.rocketmq.v2.ReconnectEndpointsCommand.Builder getReconnectEndpointsCommandBuilder() {
      return getReconnectEndpointsCommandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.ReconnectEndpointsCommandOrBuilder getReconnectEndpointsCommandOrBuilder() {
      if ((commandCase_ == 8) && (reconnectEndpointsCommandBuilder_ != null)) {
        return reconnectEndpointsCommandBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 8) {
          return (apache.rocketmq.v2.ReconnectEndpointsCommand) command_;
        }
        return apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to reconnect server use the latest endpoints.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.ReconnectEndpointsCommand reconnect_endpoints_command = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ReconnectEndpointsCommand, apache.rocketmq.v2.ReconnectEndpointsCommand.Builder, apache.rocketmq.v2.ReconnectEndpointsCommandOrBuilder> 
        getReconnectEndpointsCommandFieldBuilder() {
      if (reconnectEndpointsCommandBuilder_ == null) {
        if (!(commandCase_ == 8)) {
          command_ = apache.rocketmq.v2.ReconnectEndpointsCommand.getDefaultInstance();
        }
        reconnectEndpointsCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.ReconnectEndpointsCommand, apache.rocketmq.v2.ReconnectEndpointsCommand.Builder, apache.rocketmq.v2.ReconnectEndpointsCommandOrBuilder>(
                (apache.rocketmq.v2.ReconnectEndpointsCommand) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 8;
      onChanged();;
      return reconnectEndpointsCommandBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.NotifyUnsubscribeLiteCommand, apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder, apache.rocketmq.v2.NotifyUnsubscribeLiteCommandOrBuilder> notifyUnsubscribeLiteCommandBuilder_;
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     * @return Whether the notifyUnsubscribeLiteCommand field is set.
     */
    @java.lang.Override
    public boolean hasNotifyUnsubscribeLiteCommand() {
      return commandCase_ == 9;
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     * @return The notifyUnsubscribeLiteCommand.
     */
    @java.lang.Override
    public apache.rocketmq.v2.NotifyUnsubscribeLiteCommand getNotifyUnsubscribeLiteCommand() {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        if (commandCase_ == 9) {
          return (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_;
        }
        return apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
      } else {
        if (commandCase_ == 9) {
          return notifyUnsubscribeLiteCommandBuilder_.getMessage();
        }
        return apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    public Builder setNotifyUnsubscribeLiteCommand(apache.rocketmq.v2.NotifyUnsubscribeLiteCommand value) {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        notifyUnsubscribeLiteCommandBuilder_.setMessage(value);
      }
      commandCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    public Builder setNotifyUnsubscribeLiteCommand(
        apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder builderForValue) {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        notifyUnsubscribeLiteCommandBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    public Builder mergeNotifyUnsubscribeLiteCommand(apache.rocketmq.v2.NotifyUnsubscribeLiteCommand value) {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        if (commandCase_ == 9 &&
            command_ != apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance()) {
          command_ = apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.newBuilder((apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 9) {
          notifyUnsubscribeLiteCommandBuilder_.mergeFrom(value);
        } else {
          notifyUnsubscribeLiteCommandBuilder_.setMessage(value);
        }
      }
      commandCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    public Builder clearNotifyUnsubscribeLiteCommand() {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        if (commandCase_ == 9) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 9) {
          commandCase_ = 0;
          command_ = null;
        }
        notifyUnsubscribeLiteCommandBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    public apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder getNotifyUnsubscribeLiteCommandBuilder() {
      return getNotifyUnsubscribeLiteCommandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.NotifyUnsubscribeLiteCommandOrBuilder getNotifyUnsubscribeLiteCommandOrBuilder() {
      if ((commandCase_ == 9) && (notifyUnsubscribeLiteCommandBuilder_ != null)) {
        return notifyUnsubscribeLiteCommandBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 9) {
          return (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_;
        }
        return apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Request client to unsubscribe lite topic.
     * </pre>
     *
     * <code>.apache.rocketmq.v2.NotifyUnsubscribeLiteCommand notify_unsubscribe_lite_command = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.NotifyUnsubscribeLiteCommand, apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder, apache.rocketmq.v2.NotifyUnsubscribeLiteCommandOrBuilder> 
        getNotifyUnsubscribeLiteCommandFieldBuilder() {
      if (notifyUnsubscribeLiteCommandBuilder_ == null) {
        if (!(commandCase_ == 9)) {
          command_ = apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.getDefaultInstance();
        }
        notifyUnsubscribeLiteCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.NotifyUnsubscribeLiteCommand, apache.rocketmq.v2.NotifyUnsubscribeLiteCommand.Builder, apache.rocketmq.v2.NotifyUnsubscribeLiteCommandOrBuilder>(
                (apache.rocketmq.v2.NotifyUnsubscribeLiteCommand) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 9;
      onChanged();;
      return notifyUnsubscribeLiteCommandBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.TelemetryCommand)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.TelemetryCommand)
  private static final apache.rocketmq.v2.TelemetryCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.TelemetryCommand();
  }

  public static apache.rocketmq.v2.TelemetryCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TelemetryCommand>
      PARSER = new com.google.protobuf.AbstractParser<TelemetryCommand>() {
    @java.lang.Override
    public TelemetryCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TelemetryCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TelemetryCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TelemetryCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.TelemetryCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

