// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.UpdateOffsetRequest}
 */
public final class UpdateOffsetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.UpdateOffsetRequest)
    UpdateOffsetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateOffsetRequest.newBuilder() to construct.
  private UpdateOffsetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateOffsetRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateOffsetRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateOffsetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.Resource.Builder subBuilder = null;
            if (group_ != null) {
              subBuilder = group_.toBuilder();
            }
            group_ = input.readMessage(apache.rocketmq.v2.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(group_);
              group_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            apache.rocketmq.v2.MessageQueue.Builder subBuilder = null;
            if (messageQueue_ != null) {
              subBuilder = messageQueue_.toBuilder();
            }
            messageQueue_ = input.readMessage(apache.rocketmq.v2.MessageQueue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageQueue_);
              messageQueue_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            offset_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_UpdateOffsetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_UpdateOffsetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.UpdateOffsetRequest.class, apache.rocketmq.v2.UpdateOffsetRequest.Builder.class);
  }

  public static final int GROUP_FIELD_NUMBER = 1;
  private apache.rocketmq.v2.Resource group_;
  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   * @return Whether the group field is set.
   */
  @java.lang.Override
  public boolean hasGroup() {
    return group_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   * @return The group.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Resource getGroup() {
    return group_ == null ? apache.rocketmq.v2.Resource.getDefaultInstance() : group_;
  }
  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ResourceOrBuilder getGroupOrBuilder() {
    return getGroup();
  }

  public static final int MESSAGE_QUEUE_FIELD_NUMBER = 2;
  private apache.rocketmq.v2.MessageQueue messageQueue_;
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   * @return Whether the messageQueue field is set.
   */
  @java.lang.Override
  public boolean hasMessageQueue() {
    return messageQueue_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   * @return The messageQueue.
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageQueue getMessageQueue() {
    return messageQueue_ == null ? apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
  }
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageQueueOrBuilder getMessageQueueOrBuilder() {
    return getMessageQueue();
  }

  public static final int OFFSET_FIELD_NUMBER = 3;
  private long offset_;
  /**
   * <code>int64 offset = 3;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (group_ != null) {
      output.writeMessage(1, getGroup());
    }
    if (messageQueue_ != null) {
      output.writeMessage(2, getMessageQueue());
    }
    if (offset_ != 0L) {
      output.writeInt64(3, offset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (group_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGroup());
    }
    if (messageQueue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMessageQueue());
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, offset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.UpdateOffsetRequest)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.UpdateOffsetRequest other = (apache.rocketmq.v2.UpdateOffsetRequest) obj;

    if (hasGroup() != other.hasGroup()) return false;
    if (hasGroup()) {
      if (!getGroup()
          .equals(other.getGroup())) return false;
    }
    if (hasMessageQueue() != other.hasMessageQueue()) return false;
    if (hasMessageQueue()) {
      if (!getMessageQueue()
          .equals(other.getMessageQueue())) return false;
    }
    if (getOffset()
        != other.getOffset()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGroup()) {
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
    }
    if (hasMessageQueue()) {
      hash = (37 * hash) + MESSAGE_QUEUE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageQueue().hashCode();
    }
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.UpdateOffsetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.UpdateOffsetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.UpdateOffsetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.UpdateOffsetRequest)
      apache.rocketmq.v2.UpdateOffsetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_UpdateOffsetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_UpdateOffsetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.UpdateOffsetRequest.class, apache.rocketmq.v2.UpdateOffsetRequest.Builder.class);
    }

    // Construct using apache.rocketmq.v2.UpdateOffsetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (groupBuilder_ == null) {
        group_ = null;
      } else {
        group_ = null;
        groupBuilder_ = null;
      }
      if (messageQueueBuilder_ == null) {
        messageQueue_ = null;
      } else {
        messageQueue_ = null;
        messageQueueBuilder_ = null;
      }
      offset_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_UpdateOffsetRequest_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.UpdateOffsetRequest getDefaultInstanceForType() {
      return apache.rocketmq.v2.UpdateOffsetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.UpdateOffsetRequest build() {
      apache.rocketmq.v2.UpdateOffsetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.UpdateOffsetRequest buildPartial() {
      apache.rocketmq.v2.UpdateOffsetRequest result = new apache.rocketmq.v2.UpdateOffsetRequest(this);
      if (groupBuilder_ == null) {
        result.group_ = group_;
      } else {
        result.group_ = groupBuilder_.build();
      }
      if (messageQueueBuilder_ == null) {
        result.messageQueue_ = messageQueue_;
      } else {
        result.messageQueue_ = messageQueueBuilder_.build();
      }
      result.offset_ = offset_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.UpdateOffsetRequest) {
        return mergeFrom((apache.rocketmq.v2.UpdateOffsetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.UpdateOffsetRequest other) {
      if (other == apache.rocketmq.v2.UpdateOffsetRequest.getDefaultInstance()) return this;
      if (other.hasGroup()) {
        mergeGroup(other.getGroup());
      }
      if (other.hasMessageQueue()) {
        mergeMessageQueue(other.getMessageQueue());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.UpdateOffsetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.UpdateOffsetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private apache.rocketmq.v2.Resource group_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder> groupBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     * @return Whether the group field is set.
     */
    public boolean hasGroup() {
      return groupBuilder_ != null || group_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     * @return The group.
     */
    public apache.rocketmq.v2.Resource getGroup() {
      if (groupBuilder_ == null) {
        return group_ == null ? apache.rocketmq.v2.Resource.getDefaultInstance() : group_;
      } else {
        return groupBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public Builder setGroup(apache.rocketmq.v2.Resource value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        group_ = value;
        onChanged();
      } else {
        groupBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public Builder setGroup(
        apache.rocketmq.v2.Resource.Builder builderForValue) {
      if (groupBuilder_ == null) {
        group_ = builderForValue.build();
        onChanged();
      } else {
        groupBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public Builder mergeGroup(apache.rocketmq.v2.Resource value) {
      if (groupBuilder_ == null) {
        if (group_ != null) {
          group_ =
            apache.rocketmq.v2.Resource.newBuilder(group_).mergeFrom(value).buildPartial();
        } else {
          group_ = value;
        }
        onChanged();
      } else {
        groupBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public Builder clearGroup() {
      if (groupBuilder_ == null) {
        group_ = null;
        onChanged();
      } else {
        group_ = null;
        groupBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public apache.rocketmq.v2.Resource.Builder getGroupBuilder() {
      
      onChanged();
      return getGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    public apache.rocketmq.v2.ResourceOrBuilder getGroupOrBuilder() {
      if (groupBuilder_ != null) {
        return groupBuilder_.getMessageOrBuilder();
      } else {
        return group_ == null ?
            apache.rocketmq.v2.Resource.getDefaultInstance() : group_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Resource group = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder> 
        getGroupFieldBuilder() {
      if (groupBuilder_ == null) {
        groupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Resource, apache.rocketmq.v2.Resource.Builder, apache.rocketmq.v2.ResourceOrBuilder>(
                getGroup(),
                getParentForChildren(),
                isClean());
        group_ = null;
      }
      return groupBuilder_;
    }

    private apache.rocketmq.v2.MessageQueue messageQueue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder> messageQueueBuilder_;
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     * @return Whether the messageQueue field is set.
     */
    public boolean hasMessageQueue() {
      return messageQueueBuilder_ != null || messageQueue_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     * @return The messageQueue.
     */
    public apache.rocketmq.v2.MessageQueue getMessageQueue() {
      if (messageQueueBuilder_ == null) {
        return messageQueue_ == null ? apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
      } else {
        return messageQueueBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public Builder setMessageQueue(apache.rocketmq.v2.MessageQueue value) {
      if (messageQueueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageQueue_ = value;
        onChanged();
      } else {
        messageQueueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public Builder setMessageQueue(
        apache.rocketmq.v2.MessageQueue.Builder builderForValue) {
      if (messageQueueBuilder_ == null) {
        messageQueue_ = builderForValue.build();
        onChanged();
      } else {
        messageQueueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public Builder mergeMessageQueue(apache.rocketmq.v2.MessageQueue value) {
      if (messageQueueBuilder_ == null) {
        if (messageQueue_ != null) {
          messageQueue_ =
            apache.rocketmq.v2.MessageQueue.newBuilder(messageQueue_).mergeFrom(value).buildPartial();
        } else {
          messageQueue_ = value;
        }
        onChanged();
      } else {
        messageQueueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public Builder clearMessageQueue() {
      if (messageQueueBuilder_ == null) {
        messageQueue_ = null;
        onChanged();
      } else {
        messageQueue_ = null;
        messageQueueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public apache.rocketmq.v2.MessageQueue.Builder getMessageQueueBuilder() {
      
      onChanged();
      return getMessageQueueFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    public apache.rocketmq.v2.MessageQueueOrBuilder getMessageQueueOrBuilder() {
      if (messageQueueBuilder_ != null) {
        return messageQueueBuilder_.getMessageOrBuilder();
      } else {
        return messageQueue_ == null ?
            apache.rocketmq.v2.MessageQueue.getDefaultInstance() : messageQueue_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder> 
        getMessageQueueFieldBuilder() {
      if (messageQueueBuilder_ == null) {
        messageQueueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.MessageQueue, apache.rocketmq.v2.MessageQueue.Builder, apache.rocketmq.v2.MessageQueueOrBuilder>(
                getMessageQueue(),
                getParentForChildren(),
                isClean());
        messageQueue_ = null;
      }
      return messageQueueBuilder_;
    }

    private long offset_ ;
    /**
     * <code>int64 offset = 3;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 3;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.UpdateOffsetRequest)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.UpdateOffsetRequest)
  private static final apache.rocketmq.v2.UpdateOffsetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.UpdateOffsetRequest();
  }

  public static apache.rocketmq.v2.UpdateOffsetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateOffsetRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateOffsetRequest>() {
    @java.lang.Override
    public UpdateOffsetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateOffsetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateOffsetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateOffsetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.UpdateOffsetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

