name: Feature Request
title: "[Feature] New feature title"
description: Suggest an idea for this project.
labels: [ "type/new feature" ]
body:
  - type: textarea
    attributes:
      label: Is Your Feature Request Related to a Problem?
      description: Please Describe It.
      placeholder: >
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Solution You'd Like
      description: Describe how you solved it.
      placeholder: >
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe Alternatives You've Considered
      description: Describe your solution
      placeholder: >
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Additional context.
      placeholder: >
        Add any other context about the problem here.
    validations:
      required: false
